### ISSUE TITLE
How can i solve this problem

### ISSUE THREAD

**Issue by kakkuk** [quran/quran_android#1003]
can some one help me please
please visit this url:
https://stackoverflow.com/questions/53150362/android-draw-custom-view-and-resize-to-fit-screen

**Comment by mouss-delta** [comment]
Hi,
Are you sure the coordinates of your rectangles are right?

**Comment by ahmedre** [comment]
the coordinates are for the image assuming that its exact, unscaled size. in order to make it work, you have to scale the coordinates according to the scaling of the screen - so for example, if the image is 1000x1000 but you are showing it on the screen as 500x500, you need to divide the x and y by 2 for it to be correct.
