### ISSUE TITLE
Indonesian Translation Issues

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1005]
from an email:

>  Please correct Indonesian translation of the Qur'an Surah Yunus verse 21. Sentence translation for final passage, no.

**Comment by ahmedre** [comment]
> Just read recently surah Al-Insan : 30, and found that the translation needs little correction. 

> It is written in the Qur’an Droid app as following:
> وَمَا تَشَاءُونَ إِلَّا أَنْ يَشَاءَ اللَّهُ ۚ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا

> (Bahasa Indonesia)
> Tetapi kamu tidak mampu (menempuh jalan itu), kecuali apabila Allah kehendaki Allah. Sungguh, Allah Maha Mengetahui, Mahabijaksana.

> -Sura Al-Insan, Ayah 30

> "..., kecuali apabila Allah kehendaki Allah." 
> (double "Allah") 

> It should be:
> "..., kecuali apabila Allah kehendaki."
> Or:
> "..., kecuali apabila dikehendaki Allah."

> The last one is preferred as it is found in my Qur'an with Indonesia translation. 

> Here is I attach screenshot from the app and a photograph of the translation in my Qur’an, for your review.

**Comment by ahmedre** [comment]
> Please update Indonesian translation for Noah letter paragraph 5. Instead of "day and night" but "night and day"

**Comment by ahmedre** [comment]
> The translation in surah was wrong for al-'ashr it should be 'masa' not 'waktu sore' isn't it?

**Comment by ahmedre** [comment]
check sura fussilat 35

**Comment by ahmedre** [comment]
check sura yunus 108

**Comment by ahmedre** [comment]
> Terdapat kesalahan link untuk Juz 7 yang mestinya mulai halaman 122, akan tetapi link tersebut menuju halaman 121 yang mana masih juz 6.

> Terdapat kesalahan Link, untuk juz 11 yang mestinya halaman 202 tetapi link terarahkan ke halaman 201.

**Comment by ahmedre** [comment]
check 11:63

**Comment by ahmedre** [comment]
check 33:59

**Comment by ahmedre** [comment]
>Surah Al-Insan verse 30 (76:30) that says 

>"وَمَا تَشَاءُونَ إِلَّا أَنْ يَشَاءَ اللَّهُ ۚ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا

>(Bahasa Indonesia)
>Tetapi kamu tidak mampu (menempuh jalan itu), kecuali apabila Allah kehendaki Allah. Sungguh, Allah Maha Mengetahui, Mahabijaksana.

>-Sura Al-Insan, Ayah 30

>The mistake is in the sentence
>"kecuali apabila Allah kehendaki Allah."
>Which has an extra word of "Allah" at the end of it and should be removed to make the sentence meaningful.

**Comment by ahmedre** [comment]
sura qasas ayah 82 is missing?

**Comment by ahmedre** [comment]
17:110 - some strange characters in "Asma'ul Husna"

**Comment by ahmedre** [comment]
check sura insan ayah 30

**Comment by ahmedre** [comment]
check sura a3raf ayah 13

**Comment by ahmedre** [comment]
sura yunus ayah 21 - missing:
Sesungguhnya malaikat-malaikat Kami mencatat tipu dayamu.

**Comment by fikr4n** [comment]
How/where to correct ayah translation issue?

By the way:

> The translation in surah was wrong for al-'ashr it should be 'masa' not 'waktu sore' isn't it?

Seems it had been fixed.

**Comment by asyazwan** [comment]
> How/where to correct ayah translation issue?
> 
> By the way:
> 
> > The translation in surah was wrong for al-'ashr it should be 'masa' not 'waktu sore' isn't it?
> 
> Seems it had been fixed.

There is local sqlite db for every translation that you download. Download the latest and check against the db, then write the sql patch for @ahmedre. I'm not sure if it's the best example, but you can see how I did it for Malaysia: https://github.com/quran/quran_android/issues/321#issuecomment-396816543

Hope that helps.

**Comment by fikr4n** [comment]
Bismillah. Long time, Allah gives me power to correct these translation issues tonight.

Here is my feedback and patch for all the reports above. For some of them, I provide the update SQL script (for those marked with "done"). For some of them, I commented out because I am not sure to update it.

- 10:21, p 211 - done ✅
- 76:30, p 580 - done ✅
- 71:5, p 570 - the printed Quran is also reversed/inverted like this, day and night
- 103:1, p 601 - looks like it has been updated before
- 41:35, p 480 - no significant difference with the printed Quran, maybe it has been updated
- 10:108, p 221 - different word order, but same meaning
- 11:63, p 229 - different spell of name, but same meaning, Saleh vs Shalih
- 33:59, p 426 - no significant difference, but the printed Quran has footnote on definition of jilbab
- 28:82, p 395 - done ✅
- 17:110, p 293 - done ✅, maybe it was because there are non-ascii characters that are incorrectly encoded, here I use ascii only Asma'ul Husna to be safe, instead of Asmā‘ul Ḥusnā, what do you think?
- 4:92, p 93 - no significant difference; however I found a "bug" in one of the printed Quran I use, it's written that the killer should be handed over, there are missing words (indicated by imbalance brackets), it should be the diyat that should be handed over, like in the app and in the other printed Quran
- 7:13, p 152 - nothing strange

Thanks @asyazwan for the example

## Attachment
- [quran.id.update.sql.txt](https://github.com/quran/quran_android/files/3364815/quran.id.update.sql.txt) - update script

**Comment by fikr4n** [comment]
About report about Juz 7 and Juz 11

> Terdapat kesalahan link untuk Juz 7 yang mestinya mulai halaman 122, akan tetapi link tersebut menuju halaman 121 yang mana masih juz 6.
> 
> Terdapat kesalahan Link, untuk juz 11 yang mestinya halaman 202 tetapi link terarahkan ke halaman 201.

Not all of the printed Qurans in Indonesia explicitly marks the start of both Juz and Hizb, so I take one sample of the Indonesia-printed Quran that explicitly marks them. Here we see that in this Indonesia-printed one, the start of the Juz is at the top of the page despite the start of the Hizb. However in Madinah-printed one, the start of Juz equals to the start of Hizb, although it's not at the top of the page.

- Juz 2 (Indonesia), start of Juz equals to start of Hizb, because it's at the top of the page:
![Juz 2 Indonesia](https://user-images.githubusercontent.com/5564999/60762934-e38fce80-a093-11e9-95f5-e7773133741e.jpeg)

- Juz 4 (Indonesia), start of Juz one ayah before the start of Hizb:
![Juz 4 Indonesia](https://user-images.githubusercontent.com/5564999/60762979-d45d5080-a094-11e9-91d6-66a6b71974ec.jpeg)

- Juz 7 (Indonesia), start of Juz one ayah after the start of Hizb:
![Juz 7 Indonesia](https://user-images.githubusercontent.com/5564999/60762990-14bcce80-a095-11e9-90e6-a1684331df87.jpeg)

- Juz 7 (Madinah), start of Juz equals to start of the Hizb despite the position in the page:
![Juz 7 Madinah](https://user-images.githubusercontent.com/5564999/60763008-71b88480-a095-11e9-8a88-0852bfae71a3.jpeg)

Because this app is Madani by default, so I think the bug report may be rejected.

**Comment by fikr4n** [comment]
New bug report at **Al-Qasas (28): 15**

The first character is missing, it should be "Dan" instead of "an".

Update script:

```sql
UPDATE verses
SET text='Dan dia (Musa) masuk ke kota (Memphis) ketika penduduknya sedang lengah, maka dia mendapati di dalam kota itu dua orang laki-laki sedang berkelahi; yang seorang dari golongannya (Bani Israil) dan yang seorang (lagi) dari pihak musuhnya (kaum Fir‘aun). Orang yang dari golongannya meminta pertolongan kepadanya, untuk (mengalahkan) orang yang dari pihak musuhnya, lalu Musa meninjunya, dan matilah musuhnya itu. Dia (Musa) berkata, “Ini adalah perbuatan setan. Sungguh, dia (setan itu) adalah musuh yang jelas menyesatkan.”'
WHERE sura=28 AND ayah=15;
```

**Comment by ahmedre** [comment]
salam 3alaikum,
jazakumAllah khairan @fikr4n - i've ran this and updated these locally. may you double check the remaining ones against https://quranenc.com/en/browse/indonesian_sabiq/28 - i've checked the ones you already corrected and they match masha'Allah, so was wondering if you would check the others as well. otherwise can just go ahead and update the database with this.

for the juz' - i think i fixed this issue. the problem was that in the madani mushaf, juz' 7 as you showed in the picture is in the bottom part of the page (same with juz' 11). the original version long ago would show the actual page the juz' is on, whereas the mushaf shows the next page. i've since updated it to match the mushaf.

really appreciate your help here - jazakAllah khairan! also, jazakAllah khairan @asyazwan.

walsalam 3alaikum.

**Comment by fikr4n** [comment]
Quranenc.com also uses non-ASCII "Asmā’ul Ḥusnā" instead of "Asmaul Husna". Should we also use that?

These are the comparisons of ayahs that were commented out in my post before (quranenc.com vs one of the printed mushaf here):

Sura:Ayah | Page | Comparison of quranenc.com to printed
--------- | ---- | -------------------------------------
71:5      | p570 | Similar
10:108    | p221 | Similar
11:63     | p229 | Printed spells prophet name as "Saleh" instead of "Salih"
33:59     | p426 | Similar, including the footnote
4:92      | p93  | Printed writes "Jika dia (yang terbunuh) dari kaum yang memusuhimu," instead of "... (si terbunuh) ..."
| | | Printed spells "tobat" instead of "taubat"
| | | Printed spells "Mahamengetahui" instead of "Maha Mengetahui"
7:13      | p152 | Similar

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khairan.
i can try re-adding Asmā’ul Ḥusnā - in our sqlite file it was not readable, so looks like the encoding might have been wrong.

should i worry about 11:53/4:92 or just applying your sqlite file is enough?
walsalam 3alaikum.

**Comment by fikr4n** [comment]
> should i worry about 11:53/4:92 or just applying your sqlite file is enough?

Both these ayahs are not included in my SQL script before. In Bahasa Indonesia, these are not significant difference, just different spelling and choice of words.

**Comment by ahmedre** [comment]
jazakAllah khairan, really appreciate it. i've pushed these changes al7amdulillah. closing this for now.

**Comment by fikr4n** [comment]
Should new issues be posted here or just open a new issue?
