### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Bakhrom** [quran/quran_android#1210]
When using in Uzbekistan, there are problems with the download, it probably appeared after blocking Facebook in 2018. When using custom dns (1dot1dot1dot1.cloudflare-dns.com), the application works with mobile internet. Otherwise, only with VPN. Is there any way to solve this problem from the application side?

**Comment by ibragimof** [comment]
The same problem. Please, fix it for users from Uzbekistan.
![Screenshot_2019-12-02-17-18-58-461_com quran labs androidquran](https://user-images.githubusercontent.com/47029060/69982267-d9e09900-1555-11ea-9ff6-0a5fc3351b5f.jpg)
![Screenshot_2019-12-02-17-17-08-995_com quran labs androidquran](https://user-images.githubusercontent.com/47029060/69982268-da792f80-1555-11ea-8b53-4eb77fa6ef67.jpg)

**Comment by ozbek** [comment]
ATM, [setting up Cloudflare DNS](https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/android/) by end users seems to resolve the issue.

**Comment by ibragimof** [comment]
Updating in client side not resolved the problem. Still connection possible via vpn (and only).

**Comment by ahmedre** [comment]
salam 3alaikum,
@ibragimof i just set up a test that goes to cloudflare after the first failure so that the files download through cloudflare instead of directly through our servers - may you try this apk out (it should be installable side by side with the production one so you don't lose any data) and see if you can download the initial set of images with it and let me know?

http://cafesalam.net/uploads/quran-test-cloudflare.apk

if it doesn't work, may you go to settings -> advanced -> send logs and send us the logs?
jazakumAllah khairan,
walsalam 3alaikum

**Comment by ozbek** [comment]
ping @Bakhrom

**Comment by Bakhrom** [comment]
Page loading working, but audio, translations, "Page Type (experimental)" not working
[Logs.txt](https://github.com/quran/quran_android/files/5722574/Logs.txt)

![scr1](https://user-images.githubusercontent.com/9442259/102744764-5ff79980-437c-11eb-9ee0-51c9630a0365.jpg)
![scr2](https://user-images.githubusercontent.com/9442259/102744770-6128c680-437c-11eb-9568-e9408d4f25e1.jpg)
![src3](https://user-images.githubusercontent.com/9442259/102744775-62f28a00-437c-11eb-89a7-979fd95b36ed.jpg)
![scr4](https://user-images.githubusercontent.com/9442259/102744771-61c15d00-437c-11eb-97ef-eea2d9854208.jpg)
![scr5](https://user-images.githubusercontent.com/9442259/102744772-61c15d00-437c-11eb-867c-41ee5dae01e5.jpg)

**Comment by ahmedre** [comment]
jazakumAllah khairan for testing this - i am glad the download works - this is promising in sha' Allah since it brings the hope of being able to fix this for people in Uzbekistan closer. unfortunately, i cannot use this solution in production because the terms of service for Cloudflare don't allow its usage for non-web (css/js/...) type traffic, and it can result in termination of the account.

i made a small app that tries to load an image from our server in several different ways - may you try all of these out and post the logs at the end?

it looks something like this:

<img width="647" alt="Screen Shot 2020-12-21 at 9 11 14 PM" src="https://user-images.githubusercontent.com/47771/102803050-14230f80-43d1-11eb-86f6-74cd86a9aa4a.png">

you can find it here:

http://cafesalam.net/uploads/network-test.apk

jazakumAllah khairan!
walsalam 3alaikum.

**Comment by Bakhrom** [comment]
[Logs-netwok.txt](https://github.com/quran/quran_android/files/5727826/Logs-netwok.txt)
First three items not worked

**Comment by ahmedre** [comment]
al7amdulillah awesome! got a solution then for the next version in sha' Allah, may Allah reward you greatly!

**Comment by Bakhrom** [comment]
Jazakumullohu khoyron kasiro

**Comment by ahmedre** [comment]
i've made the changes and updated the actual Quran app - may you try this out?
http://cafesalam.net/uploads/quran-updated-servers.apk

it should (in sha' Allah) work for pages, translations, page types, and (hopefully in sha' Allah) audio.

for audio, because there are 2 separate urls, can you try at least one gapless sheikh and one gapped sheikh?

jazakumAllah khairan!

**Comment by Bakhrom** [comment]
Loading pages, audio and experimental pages work. Only when loading each ayah, it waits a little with an error (Network error, resume downloading) then loads this ayah, it would be nice if it was not possible to connect to the main url, then use falbak url in this session, But main things that everything works. Submitting logs doesn't work, so I was unable to submit logs.

Jazakumullohu khoyron kasiro!

**Comment by ahmedre** [comment]
awesome to hear, jazakumAllah khairan!
i'll implement your suggestion of going to the fallback by default after the fallback succeeds once in sha' Allah.

**Comment by Bakhrom** [comment]
Thank you

**Comment by ahmedre** [comment]
this is now being released, should get the update within the next few days if you haven't already - closing for now.
jazakumAllah khairan for your help!
