### ISSUE TITLE
[Bug Report ] :Quran data directory Disabled

### ISSUE THREAD

**Issue by thoraiia** [quran/quran_android#1212]
I have Lenovo tab2
the Quran data directory option is disabled

1. I uninstalled and reinstalled the app many times, but still the same issue.
2.  I tried to move the Quran android folder from the internal storage to the SD card, but the application can't read it and asks me to install the data again, and it consumes about 4GB from the internal storage and slows down the tablet (audio files + Translations ).
3.   I tried by (factory resetting the tablet ) but still the same Problem

**Comment by ahmedre** [comment]
jazakAllah khairan.
i want to make sure i understand correctly - you start the app, download the initial data, and then go to settings and switch it to use one of the external sdcards. when you restart the app, it doesn't work? 

would appreciate clarification so in sha' Allah can try to fix this if it's an issue here.

**Comment by thoraiia** [comment]
tablet settings -> default storage -> SD Card
when I download the app -> it was downloaded on the internal storage
so I went back to settings -> applications -> Quran android->move to SD card
then when I check the folder from the ( file manager) it's still in the internal storage
----------
I opened the app->say no to data download -> setting -> advanced settings -> but the Quran data directory button is always disabled
then closed the app -> reopen the app -> say yes to data download -> and everything is in my internal storage
I tried to move the Quran android folder from the internal storage to the SD card, but the application can't read it and asks me to install the data again, and it consumes about 4GB from the internal storage and slows down the tablet (audio files + Translations ).
then uninstalled and re-installed the app many times but the same issue

**Comment by ahmedre** [comment]
hmm - sounds like it's failing to copy to the external storage for some reason. can i send you a debug build that you can try that will let me know what's happening here so i can see if i can fix it somehow?

**Comment by thoraiia** [comment]
ok

**Comment by ahmedre** [comment]
please try [this apk](http://cafesalam.net/uploads/app-madani-debug.apk) - make sure you uninstall your current one first. run this one, try to copy the data and as soon as you finish copying, before you exit and restart the app, go back to "advanced settings" and choose "report logs" and email them to quranandroid at gmail with "logs for issue 1212" in the title and please update me when you do so i can check.

jazakAllah khairan.

**Comment by thoraiia** [comment]
done

- I uninstalled the version from google play
- downloaded your version
- before installing I was asked to choose the storage location (internal storage - SD card) I choose SD_card
- downloaded the Quran pages
- advanced settings -> and sent the logs
did I do the steps right way?

**Comment by ahmedre** [comment]
almost - but you didn't try moving the files to the sdcard so that part is not in the logs. so may you move the pages to the sdcard and then send the logs?

**Comment by thoraiia** [comment]
the button is disabled [unclickable]

**Comment by ahmedre** [comment]
i made some small changes - may you try to [install this file](http://cafesalam.net/uploads/app-madani-debug.apk) - i think it will still be disabled, so just open advanced prefs and send the logs over so i can understand why it's disabled.

also, one question: did you upgrade Android on your tablet recently?

jazakumAllah khairan.

**Comment by thoraiia** [comment]
done

- I uninstalled the first version u gave me
- deleted the data files from the internal storage (file manager) manually
- downloaded your latest version
- downloaded the data
- and sent the logs [ the button was unclickable]

No, I didn't, I did a factory reset today, and my current android version is 5.1

**Comment by ahmedre** [comment]
so in the newer versions of Android (Kitkat and above), there's an api we're supposed to use to get the list. this api is now returning only one path in your case (the internal storage), which is why it's grayed out. if it wasn't grayed out with the play store version, i guess you may have had an older version of Quran for Android before we changed this logic.

we could theoretically enable that again but it's risky since it might not allow us to write files on there anymore (which is what i guess might have been happening before?)

if you're interested, we can see if that works. if it does, we can figure out a way to make this an option for newer versions as well. please feel free to [try this one](http://cafesalam.net/uploads/app-madani-debug.apk) again and see if it works. move the data and then send the logs. if the option is still disabled, then please also send the logs anyway.

**Comment by ahmedre** [comment]
ok, i see why it failed this time around - can you see if [this one](http://cafesalam.net/uploads/app-madani-debug.apk) fixes it?

**Comment by thoraiia** [comment]
the button is active -> SD_card -> failed to move app files

**Comment by ahmedre** [comment]
one last thing i can think of - go to Android settings (not in the app, the tablet's settings). then go to applications, and then go to Quran for Android. there should be a "permissions" - please click it and make sure that all permissions are given. then try again.

**Comment by thoraiia** [comment]
Settings->Apps -> app name->permission section {only displays permessions}
this app can access the following on your tablet:

- modify or delete the contents of your SD card
- read the contents of your SD card
- full network access
- View network connection
- prevent tablet from sleeping

Jazak Allah khairan for your time, I do appreciate it

**Comment by ahmedre** [comment]
so the first 2 were already checked as enabled, right? and it still failed during the copy?

**Comment by thoraiia** [comment]
yeah

**Comment by ahmedre** [comment]
in that case, there's nothing i can do :(

sadly, it seems to be failing because the app doesn't have write permissions to write on that drive (which is why on the newer version, we disable the option overall). we check if the directory exists, and if it doesn't, we try to create it. the creation of the directory is failing here, making it seem like we don't have write permission to this external sdcard (even though you granted sdcard write permissions).

Google has been tightening down on where we can and can't write, and previously, we were using a set of hacks that are no longer working on newer versions. i unfortunately can't think of a way to fix this :(

**Comment by thoraiia** [comment]
ok 👍 , Jazak Allah Khairan

**Comment by ahmedre** [comment]
waiyyakum
