### ISSUE TITLE
New Madani ayah numbers

### ISSUE THREAD

**Issue by fauzie811** [quran/quran_android#1219]
السلام عليكم

I'm trying to make a Quran app of my own using the new madani images. But I couldn't find where does the drawing of the ayah numbers happen in the code? Because there's no ayah numbers in the image.

![page604](https://user-images.githubusercontent.com/318095/67435874-4ee7b700-f617-11e9-98c3-99bd3baaac32.png)

I'm not used to big projects like this, so I must've missed something.

Thank you for your help.

جزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمه الله،
The app does draw the Ayah numbers. However, that code isn’t in the repository. I’ve avoided making some things open due to the many many apps that come up using the code with minor changes (while monetize with ads and using our servers for data, therefore adding to our costs).

والسلام عليكم.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fauzie811** [comment]
Oh. That makes sense. I guess, I have to figure it out myself then.

Thank you.

**Comment by fauzie811** [comment]
I'm sorry. But could please at least give us a hint on how you did that?

Thank you.

**Comment by alefsoft1** [comment]
ای ول

**Comment by fauzie811** [comment]
Nevermind. I figured it out.

For anyone wondering, it's actually pretty simple. Because the coordinates are already there in the database. You just need to draw the numbers accordingly.

**Comment by ahmedre** [comment]
as a reminder, please remember that the policy for using the code is to not add ads to your fork nor to charge for it. there's a reason some of that code is not open which is that i don't want to make it easy for people who have been doing this to continue doing so. please do not do this.
