### ISSUE TITLE
Add other reciter 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1279]
I created new timing file for sheikh Ahmed Alajami, I need your help to add this sheikh tilawa 

ahmed_ibn_3ali_al-3ajam.db
I sent this file by email to quranandroid@gmail.com 

Bellow the link of mp3 s files

http://download.quranicaudio.com/quran/ahmed_ibn_3ali_al-3ajamy/

**Comment by nacer80** [comment]
quran.android@gmail.com

Email corrected

**Comment by nacer80** [comment]
Please I need you help to add this sheikh to quran for android app reciters list

**Comment by ozbek** [comment]
Assalamu alaikum

Adding a new reciter involves several people, please give it a some time :)

**Comment by nacer80** [comment]
Wa3likom aslam brother
I have a data base timing file for sheikh Ahmed Alajami, "ahmed_ibn_3ali_al-3ajam.db"
I tested it, it worked perfectly 
I can share it with any one.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
received your email brother. many people have asked for sheikh Ajamy over time and i haven't added him (despite having the timing files already, etc) because of tajweed issues. will think about it again and perhaps will add him in sha' Allah.

jazakAllah khair for sending the files.
walsalam 3alaikum

**Comment by nacer80** [comment]
Wafikom barak allah
Inshallah
We hope that you add also sheikh ma3igli gapless  recitation 

Jasakom Allaho kheira
