### ISSUE TITLE
Helping out for the warch version.

### ISSUE THREAD

**Issue by Nelnaji** [quran/quran_android#1280]
A salamu alaikum to you all!
I would like to help you implement the warch version,
I don't know how to code, But I have 2 copies of the maghribi qur'an in riwayat warch An nafi'i, one with tajweed, and the other normal, both in Khat Uthmani, if you need pictures I can do so.
I also have time to offer, so if what's preventing you from implementing the warch version is not copies of the qur'an and something else, I'm willing to learn under guidance and help with heavy repetitive work!

I found this looking through your previous conversation https://furqan.co/m-warsh-text/1/1
So it seems to be a good version, Please tell me How I can help, i'm going crazy trying to find a warch versions with 1/6 hizb partition.

**Comment by Hiyaro** [comment]
Hey sorry for the delayed answer.
I looked up, and this is the version you're using http://www.quranflash.com/books/Warsh2/?en#sthash.YDmANq0L.dpbs   Qur'an Warch With a kuffi scripture.
As the basmalah is included in surat al fatiha 
ALif lam mim is also counted as an ayat etc...
https://imgur.com/a/hX0WC

While in all morocco and many countries this is the version used http://www.quranflash.com/books/Warsh1/?en#sthash.H7hyi0jN.dpbs Qur'an warch with a madinan scripture.
the basmalah isn't considered an aya in surat al fatiha, and neither the alif lam mim in surat al baqara.

In kuffic scripture surat al baqara has 286 ayat, surat al kahf has 110 ayat.
In medinan scripture surat al baqara has 285 ayat, surat al kahf has 105 ayat.

It's not a really big problem. as I have a qur'an warch that also has the kuffi scripture.
https://imgur.com/VavbFDf
But what is bothering me is that it has taqsim of 1/8 of hizb. that is different.
here'shttps://imgur.com/ikvfpUJ a picture to help you understand.
You can also just compare http://www.quranflash.com/books/Warsh1/?en#sthash.H7hyi0jN.dpbs
and http://www.quranflash.com/books/Warsh2/?en#

To see what I am talking about.

**Comment by Hiyaro** [comment]
Hey I feel like you forgot about our conversation.
are there no plans to implement a warch 'an Nafi' mushaff tariq al azraq? it is the most used version.
I still would love to help but as I said I have no idea what to do, if you were to direct me. that would be great.

Take care of yourself. and thank you again for the tremendous work you put!

**Comment by ahmedre** [comment]
salam 3alaikum,
sure - not against adding this within the existing warsh app so it can switch between both the kufi and azraq versions. may you point me to some images? if these are good resolution images, i can run the ayah detection scripts on them - after that would just need some help with the equivalent of [MadaniDataSource](https://github.com/quran/quran_android/blob/master/common/data/src/main/java/com/quran/data/pageinfo/common/MadaniDataSource.kt) for Warsh to take into account these changes in ayah numbers, etc.

jazakAllah khairan,
walsalam 3alaikum.

**Comment by Hiyaro** [comment]
Wa alaykumu salam,
I found multiple versions. I could also scans the one at home, or the big ones in my mosques; But I do not own the rights, so i'll reach out monday to the respectiv associations to ask for the rights...
I found this https://fonts.qurancomplex.gov.sa/wp02/%D8%AE%D8%B7-%D9%88%D8%B1%D8%B4#05
I don't know if this is helpful to you or not.
Take care of yourself, and thank you for the quick answer.

**Comment by ahmedre** [comment]
alsalam 3alaikum - Ramadan Mubarak.
JazakAllah khairan - we can either do an options within the Warsh app to choose (or we can just merge them both into the main app).

What do you suggest we do? I can help with the ayah detection if you can get me a set of images for it. Also, I am wondering if we should switch out the current warsh version - for example, one person reported that sura Yunus ayah 103, al mu'mineen has a hamza on it - I checked both the azraq and asbahani versions (and both versions on nquran) and neither has this hamza even though our version (https://android.quran.com/data/warsh/width_1024/page220.png) does.

I know the pages we're using come from Tunisia, but I'd rather stick with the official King Fahd versions if so - so can you help in replacing both these sets? What should you suggest?

JazakAllah khairan.
walsalam 3alaikum.

**Comment by Hiyaro** [comment]
Wa Alaykumu Salam- Ramadan Mubarak to you aswell!

I just checked and the version seems to be the correct one.  Did you change it?

I've tried to reach king Fahd complex, for the Azraq tariq, but my email is bouncing back.
I also tried to reach the Morrocan association. But they have a script protecting their e-mail adress. 
I think I need to muster the courage to call them both.
Sorry for taking so long to answer, time fly so fast, I didn't notice 18 days had already pass.

If I get the permission for the tariq azraq, I think the best would be to merge both in one, or even merge them with the principal.

tomorrow 14/05/2020 by the end of the day i'll tell you If i was able to reach them!

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullah -
good news - al7amdulillah i got the King Fahd pages and am preparing them.
https://epub.qurancomplex.gov.sa/issues/qiraat/warsh39/offline/download.pdf
walsalam 3alaikum.

**Comment by Hiyaro** [comment]
Wa alaykum Asalamu Wa rahmatullah!
Yes this one is great, except for the khat being unusual for me "Qaf, and Fae, different"
I will still reach to the association Tomorrow be idhni Allah.
It's something I would like to do.
Take care of yourself brother. and May allah makes you of those who stand in prayer during laylatul Qadr.

**Comment by ahmedre** [comment]
ameen waiyyakum - sure, and if they get back to you, we can add other warsh types also, but i would like to add this one because QuranComplex's pages are at least authorized so i can rest knowing al7amdulillah all the data is fine.

**Comment by Hiyaro** [comment]
Alright great! 
I'll stay in touch!
Thank you for your efforts!

**Comment by nacer80** [comment]
@Hiyaro
@ahmedre
Salam 3alikom 
It's very good news, and great job.
Allhamdo lillah

Jazakoum Allaho kheiren

**Comment by ahmedre** [comment]
wa3laikum alsalam,
may Allah accept from all of us, jazakumAllah khairan for your efforts!
walsalam 3alaikum.

**Comment by ahmedre** [comment]
also may Allah reward the brother who sent me the pdf link, the brother who sent me high quality images from them, and both of you for opening these issues and contributing all that you both have, and everyone else who has contributed as well to this project over the past years - jazakumAllah khairan!

**Comment by nacer80** [comment]
Salam 3alikom 
Brother I found also a version of Warsh  azrek way with tejweed in Quranic research الباحث القرآني .
You can check it if  it's Ok, we can ask brother Mustafa about it.
https://tafsir.app/

**Comment by Hiyaro** [comment]
You're talking about this one? https://tafsir.app/m-t-warsh-alazraq/37/51
It is the one I am currently using. but since it's already in this app : https://play.google.com/store/apps/details?id=com.something.ahmedlando.Almoshaf_ALMojawd_Warsh3nNafe3
I thought they Had exclusive rights to it.
I think if we were to implement it, in the app. We should have a discussion with them.

Also I've reached to the Moroccan association. and they asked me to call them back tomorrow.
As for The king fahd association, since I don't speak arabic fusha perfectly, I think it would be best to email them in english... Do they speak english in their office? I'm afraid we wont understand each other. Since I come from Morocco and our Arabic is quite different from the one used in the peninsula.

**Comment by Hiyaro** [comment]
Salam Alaykum brothers.
I've reached to the morrocan association.
Their infographist isn't available to provide high pictures of the qur'an.
They told me to wait for after the coronavirus situation...

What do you think about the version with tafsir?
The app i'm using that is utilizing those pictures. has unfortunately started implementing ads...

**Comment by ahmedre** [comment]
i'll go with the King Fahd one for now - we can add more options later in sha' Allah.

**Comment by nacer80** [comment]
Baraka Allaho fik my brother 
You're right,  go ahead

**Comment by ahmedre** [comment]
alsalam 3alaikum,
al7amdulillah i updated the app to be able to show the warsh images from King Fahd from 1440.
i uploaded a debug build here - http://cafesalam.net/uploads/warsh-beta.apk - please do try it and let me know if you run into any issues. if all is well hopefully can release this in the near future in sha' Allah.

jazakumAllah khairan.
walsalam 3alaikum.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Jazekoum Allaho kheiren my brothers 
Amazing interface Mash'Allah.
Great job, finally we have Warsh Mushaf with amazing pictures.
It's a good news for our brothers in the north Africa 

We have an issue with the sounds timing because there are some difference in Ayats order between Hafas and Warsh. I.e in Fatiha we have to move the timing of Ayah no 2 to Ayah no 1and 3 to 2.

بارك الله فيكم وجزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I hope to add more gapless recitation 
I'm preparing database files for tow famous shouiokh in Rewayet Warsh: Sheikh Qari Yassin Eljzairy and skeikh Ibrahim Doussery.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I sent the timing data files of both reciters I created the db with 6214 Ayats I checked all files are working file.
Also I sent the quran.ar.db for 6214 Ayat
We have issues with search,Tafseer and translation due to the difference in number of Ayats between Hafs 6236 Ayah and Warsh terik Alazrek 6214 Ayah.
We hope that we fix those issues Insh'Allah 
Also I sent some page from book  الثمر اليانع في رواية ورش عن نافع contains the tables of differences between Hafs and  Warsh in Ayats order. 
والسلام عليكم ورحمة الله وبركاته.

**Comment by Hiyaro** [comment]
> 
> 
> alsalam 3alaikum,
> al7amdulillah i updated the app to be able to show the warsh images from King Fahd from 1440.
> i uploaded a debug build here - http://cafesalam.net/uploads/warsh-beta.apk - please do try it and let me know if you run into any issues. if all is well hopefully can release this in the near future in sha' Allah.
> 
> jazakumAllah khairan.
> walsalam 3alaikum.

A salamu alaykum, the version presentely used is good.
The one from 1440. has an old script, that isn't taught to everyone.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i am reaching out to some brothers to see if i can't get a version that is more similar to the script used in the app today.

the problem with the current script in the app is that it has an error - and when a script has an error, there are likely more errors. if i can't find a better version, i'd rather have the old script version than have a version with errors since at the end of the day, correctness is more important.

jazakumAllah khairan for letting me know.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
salam 3alaikum,
@Hiyaro may you help me out here - can you give me some screenshots from an ideal version of the warsh mushaf to use that is not a very old script? if you have a physical copy can you take a picture of a few pages and the first few pages that describe the source (the publisher/country/etc) so we can try to get in touch with them?
jazakumAllah khairan.
walsalam 3alaikum

**Comment by Hiyaro** [comment]
Wa Alaykum A salam!

What about this one?  https://tafsir.app/m-t-warsh-alazraq/1/1 Isn't it from king fahd complexe? 

If it is not usefull i'll comply and give you the information you need.

**Comment by ahmedre** [comment]
salam 3alaikum -
@Hiyaro @nacer80 can you try this one - http://cafesalam.net/uploads/warsh_tajweed.apk - only problem is i have to figure out a good way to distribute this since it's above the 100mb limit of the play store and above the 150mb limit of app bundles - either will use play asset delivery or will make it a mandatory blocking download on start most likely. might also try to remove some of the borders around the pages and see if that helps, but let's see in sha' Allah.
walsalam 3alaikum

**Comment by Hiyaro** [comment]
A salamu Alaykum.
I got a corrupt file error with the app. 
it keeps on looping the pop et 0% "new attempt to download"
Then it stops and a new pop up shows up with Cancel and retry.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
@Hiyaro i just tried on another device and it worked fine - it shouldn't need to download anything because everything's bundled. can you remove the existing images if you have them first and then try running the app again?
jazakumAllah khairan.
walsalam 3alaikum

**Comment by Hiyaro** [comment]
@ahmedre We're good!

You did great man!

I think your idea of removing the borders is great it will reduce the size of the files, and at the same time make the text bigger.
 
I can help you out with that! Ofc I wouldn't remove the lower border.

There's also two things I noticed. 
first is [this border](https://i.imgur.com/652RLL7.jpg) that pops on the left or right of the screen. 
And second the audio files time stamps are on the hafs version.

The alif lam mim is considered an ayat. Just try it, and you'll see what I mean.

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
It works very good in my device 
About the size we can reduce it if we remove the borders around the pages as Ahmed said.
وجزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
My brother@Hiyaro 
About the audio files I sent before to brother Ahmed tow gapless reciters Sheikh Yassin Eljzairy and sheikh  Ibrahim Doussery. 
See issue #1391 
وجزاكم الله خيرا

**Comment by Hiyaro** [comment]
@ahmedre 
I am using the Beta right now...

I love you man.
Wallahi I love you!

Yeah if you need help with repetitive work of Design I can help you out, I studied design, even though it was a few years ago, I think i still got it!

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
jazakumAllah khair, glad al7amdulillah this works out well!

you can get an updated version here: http://cafesalam.net/uploads/warsh_tajweed_updated.apk

changes:
- removes 36px from right and 36px from left - this helps bring the size of the apk under 150mb al7amdulillah
- adds shuyookh Yassin Eljzairy and Ibrahim Doussery gapless from brother @nacer80 

i didn't remove the borders because i guess without the green borders on the left and right, the border makes sense, but let me know what you think?

jazakumAllah khairan.
walsalam 3alaikum.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Great job Baraka Allaho fik
1-About the border in above we remove it. Because it contains the surah name and hizeb and we have this provider from app.
2-About the border in bellow it contains the index (table) of color of tajweed meaning but repeated so we can remove it and replace it with same table 
Inside the app and  let the app repeats it in every page. 
@ahmedre what you think?

**Comment by Hiyaro** [comment]
@ahmedre 

You already did an amazing job.

the coran warch is live, isn't it?

I have a few ideas. The number of the surat should be added in the popup page.
Like there's  Sourate Al-Fatiha then page 1, Juz' 1 but not the number of the surat. or Hizb.

Something like this would be great Sourat (1) Al-Fatiha page 1, Juz' 1, Hizb 1. 

What do you think about adding a hizb repartition? https://www.le-coran.com/coran-juz-hizb.php

**Comment by Hiyaro** [comment]
السلام عليكم ورحمة الله وبركاته
@ahmedre 

If there's a tutorial for me to follow to be able to help with the app warch, let me know, I can dedicated some time to it.
and try to make the warch version as good as the hafs one.

I'de love to help out With the mistranslations and the wrong time tables. and the wrongs verse counts etc...

So if there's a tutorial outhere you think will help me understand things, just point me toward it. that way I can alleviate some of your work.

Take care of yourself akhi. a salamu Alaykum. And thank you again for following through with the tajweed version, it is overall the best one for warch an nafi' tariq al azraq(which is the most used version).
I think the title for the app should be changed really it should be qur'an warch.

and also the images for the app and the description here I took some screenshots for the app https://imgur.com/a/d4TI0uz



"
Quran for Android is a free Quran application for Android devices. There are many features under development. Please send us your feedback and feature requests and keep us in your prayers!

*Important Note* - This version is of Qur'an warsh An Nafi' Tariq al Azraq with Tajweed. It is for those who read the riwayat of Warsh. One of the 10 riwayat of the qur'an primarly used in Egypt, Morroco, Mauritania etc.... If you do not know what "Warsh" means, please download our madani or naskh app instead.

This app provides the same great features as the Madani & Naskh apps also available in the play store:

- crystal clear Warsh images (Nafe' using Al azraq's method).
- gapless audio playback
- ayah bookmarking, tagging, and sharing
- night mode
- customizable audio repeat.
- translations / tafsir in over 20 different languages, with more coming soon.

We are open to hearing your suggestions to make Quran for Android the best Quran application for Android.

"

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
Really sorry for the delayed reply and jazakumAllah khairan for the screenshots, updated description, and the feedback and suggestions.

I've been talking offline to brother Hicham who, jazahuAllah khair, gave gapless recitations for sheikh Abderrahmane Ben Moussa and others that are pending and has been testing this version also. As you mentioned @Hiyaro, there are a lot of audio issues (mostly caused by the difference between Madani and Kufi numbering).

This difference in numbering will cause a number of issues:
1. Translations - and this is the biggest one - we al7amdulillah have a large number of translations, and the Kufi numbering will be wrong for all of these. The ideal approach here is to have Warsh specific versions, but that doesn't seem feasible because of the fact that a. the splits can't be automated due to some ayahs that are 1 ayah in madani counting being 2 in kufi counting and vice versa, and b. translations change frequently when we find errors, most of which is handled by scripts to update from csv files of the various sources - doing this would add a manual set of required changes every time.

The easiest thing I can think of here is a combination of "mapping" and "grouping" functions for Warsh so we can do it in an automatic fashion:

- for example, Sura Maryam 1 and 2 in madani is ayah 1 in kufi - translation would "group" 1 and 2 for the translation of 1, and "map" 3 and beyond to ayah x + 1.
- another example, Sura Maryam 41 in madani is 2 ayas in kufi - translation would "map" 42 to 41 so that it says "see translation for 42" or something similar as happens today in some of the Arabic tafaseer.

2. Migrating people's data - suppose someone bookmarked ayah 110 of sura Kahf today (last ayah using madani counting). Tomorrow when they upgrade, what do we do? We either need a mapper to map 110 to 105 in this case or drop the bookmark. Some other cases might be tricky - ex if someone bookmarked ayah 41 of sura Maryam, what does that map to?

3. Audio - today, there's only one Qari - sheikh Ibrahim Dossary gapped - if we update to kufi numbering, people's downloaded audio would be wrong in certain cases. @nacer80 did provide gapless versions of these, but what about existing people upgrading today?

4. sharing of text

Is there no good set of pages that's both reliable and uses Madani counting that we could use? I think it would be a lot less work than writing a layer to map these (which will still not be perfect and have issues).

JazakumAllah khairan,
walsalam 3alaikum.

**Comment by Hiyaro** [comment]
There are versions that use the madani counting system for the ayats in the warch an Nafi', I have a qur'an that uses it. I don't know how reliable. And I personnaly Can't Picture them I don't have the right set up for it.

But I personnaly believe that sticking with this one would be very beneficial for this specific counting system... People could use it with these time tables. It is mostly repetitive work "mapping and grouping"

For your first point 1, I absolutely Agree, every single translation is incorrect simply because of the different counting system. 
It can be done manually, since In reality there's isn't much difference, "surat al fatiha, 1 aya difference, in surat al baqara 2 etc..."

I can do this work: checking the differences in ayat for every single surat. and pointing them out.  (as I said there isn't much difference, Many suras don't have any differences in the counting) And since I have the paper versions for both the work can be done faster on my part.  

And I think If I can do this work, you can do the mapping and grouping you're talking about. If you have already a system in place for the tables Just give me a template table for me to fill.  You could also teach me or point me toward a direction as to how to do the mapping and grouping. 


For the point number 2: I think you're talking about the ayat 40. you're right that would be a tricky, the only way around it, is to remap for those situation. You know what, I'm already going to check the differences and see how many of these tricky situations there are. that way we can decide how to do things.

For point number 3 and 4 : I do not know.

I'll work on a table of differences.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@Hiyaro 
I sent this message befor
" I sent the quran.ar.db for 6214 Ayat
We have issues with search,Tafseer and translation due to the difference in number of Ayats between Hafs 6236 Ayah and Warsh terik Alazrek 6214 Ayah.
We hope that we fix those issues Insh'Allah 
Also I sent some page from book  الثمر اليانع في رواية ورش عن نافع contains the tables of differences between Hafs and  Warsh in Ayats order"

So please check this book الثمر اليانع في رواية ورش عن 
نافع

والسلام عليكم ورحمة الله وبركاته.

**Comment by Hiyaro** [comment]
@nacer80 
Thank you for the book I looked it up, It does indeed give the differences, but it doesn't give the pages the position and the number of ayats.

I'm Already working on a table. that has all those informations, it should make the mapping and the rest of the work way easier.

https://docs.google.com/spreadsheets/d/e/2PACX-1vS1rx7DjY1TLjsDShSQNYnJdTvmLRF5tNWMbrcxEF7XdOIa_sQsPr1F9vCdi1hvcPxEwvDYKJTVD7qm/pubhtml
You can check it for yourself.

It should be completely done by either tomorrow or the day after it.
I think it will greatly help see what's going on. Also many surat only have 1 differences, I haven't wrote them down yet, I'll do so tomorrow Incha'Allah.

Wa Salamu Alaykum!

**Comment by ahmedre** [comment]
@Hiyaro jazakumAllah khairan - this table is exactly what i will need in sha' Allah - barak Allah feek. with this, a mapping layer can be written in sha' Allah. the other required data (first ayah of each page, new rob3/thomn values, etc) i already have al7amdulillah, as they were contributed from brother Hicham.

@nacer80 jazakumAllah khairan - you did, and I forgot :( but in sha' Allah this mapping layer will help us take care of things. one quick question - are your timing files for Warsh based on kufi or madani counting?

jazakumAllah khairan both!

my plan right now is to focus on releasing the long overdue update for Madani/Naskh, and then focus on writing this mapping layer and releasing a warsh update in sha' Allah.

**Comment by benomaire** [comment]
@ahmedre 
1. I like the idea of mappings, as this should allow adding [Mushaf Douri](https://qurancomplex.gov.sa/kfgqpc-quran-qiraat-douri/) for example in the future. But, I don't get how would you handle the case of ayah 41 of Sura Maryam?
We have this:
Madani	| Kufi
41		| 40
41		| 41
How would you do the split?
a. One idea is adding a hidden character in all translation files and look for it in the mapping layer when Warsh is active (the mapping layer knows that madani 41 is kufi 40-41, the character will just till it _where_ to split). That hidden character could be two or three consecutive spaces (or any other special character that does not cause problems for the app and for people copying text to somewhere else)
b. Another idea is to recreate all translation files with smallest possible ayat (which does not map to any single riwayah), and then you will do mapping for Hafs as well (I think this will be a mess). Also, millions have the Hafs copy nowadays.

2. Why persisting bookmarks across different Masahif? Make bookmarks of Hafs for Hafs, and those of Warsh for Warsh.
3. For Sheikh Ibrahim Dossary gapped:
a. write a special function that handles that case -> if done, will probably have to keep it many versions to come.
b. tell the user the files are old, and need to be redownloaded
c. add a function in our app that [recombines](https://stackoverflow.com/questions/35340025/how-to-merge-two-or-more-mp3-audio-file-in-android) and [splits](https://stackoverflow.com/questions/32462384/split-audio-file-in-android ) the current gapped mp3 files
d. remove Qari all together with the intention of adding him later. (mp3 files will be left on the device)

4. Can't we use [the text accompanying KFGQPC's Warsh font](https://fonts.qurancomplex.gov.sa/wp02/%d8%ae%d8%b7-%d9%88%d8%b1%d8%b4)?


> Is there no good set of pages that's both reliable and uses Madani counting that we could use?

I think if it is _reliable_, then it should not use Madani counting.

**Comment by benomaire** [comment]
I think the screenshots should show the Arabic version of the the Sura list along with the current one. Also, sharing, audio, dual-page mode, tafseer (not just translation)

Also, have you considered these versions of Mushaf Warsh (may be in the future along with Tajweed Mushaf)
1. [رواية ورش عن نافع من طريق الأزرق بإشراف الشيخ توفيق إبراهيم ضمرة ](http://iswy.co/e18tkq) This version requires cropping the margins, and using black for all colors.
2.  [المصحف الشريف الحسني المسبع برواية ورش](https://archive.org/details/Quran_Warsh_Moorocco)

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Good job my brothers wa jazekoum Allaho kheiren 
All files based on kufi.
I have one suggestion; I hope that we keep both Mushaf kufi (Tariq azrak عن طريق الأزرق )images with Ahkem tajweed and first version without.

![Screenshot_20201013-074041](https://user-images.githubusercontent.com/60948528/95816729-75bb6380-0d28-11eb-8137-969ed50a5249.jpg)
وجزاكم الله خيرا

**Comment by Muslim629** [comment]
> alsalam 3alaikum - Ramadan Mubarak.
> JazakAllah khairan - we can either do an options within the Warsh app to choose (or we can just merge them both into the main app).
> 
> What do you suggest we do? I can help with the ayah detection if you can get me a set of images for it. Also, I am wondering if we should switch out the current warsh version - for example, one person reported that sura Yunus ayah 103, al mu'mineen has a hamza on it - I checked both the azraq and asbahani versions (and both versions on nquran) and neither has this hamza even though our version (https://android.quran.com/data/warsh/width_1024/page220.png) does.
> 
> I know the pages we're using come from Tunisia, but I'd rather stick with the official King Fahd versions if so - so can you help in replacing both these sets? What should you suggest?
> 
> JazakAllah khairan.
> walsalam 3alaikum.

Wa AlaikumuS-Salam, my brother where you get this Mus'haf Warsh in good quality?

**Comment by Hiyaro** [comment]
A salamu Alaykum Everyone

I think we should stick with the tajweed version and work on a remapping based on it. It is by far the best version
As for the version posted by @nacer80 was it not the version previously used? the issue is the police with the qaf and Fae letters, those are not very liked.

For @benomaire 
> 
> 
>     1. [رواية ورش عن نافع من طريق الأزرق بإشراف الشيخ توفيق إبراهيم ضمرة ](http://iswy.co/e18tkq) This version requires cropping the margins, and using black for all colors.
> 
>     2. [المصحف الشريف الحسني المسبع برواية ورش](https://archive.org/details/Quran_Warsh_Moorocco)

We have considered adding other mushaf along the tajweed one, the first in actually very good. even though the quality of the pictures isn't pictures, but the second seems to be just too Stylised.


Overall the tajweed version is the most communly used one, the version of tariq al azraq is also the most known one, therefore when it comes to warsh, this mushaf we're presently using is the best IMHO. thank you again @nacer80  for linking to it, and @ahmedre for implementing it.


To go back to the table, I'm constantly updating it, If you need me to add some other information "start of the aya etc... for the work to be more efficient just tell me, and i'll do so

I think the work should be done starting from the small surat, they regroup almost all case scenarios and it would be a great training for the remapping/grouping/splitting honnestly the more I look up the differences the more I see how uncomplicated it is. only a few small parts need a remap of 1 verse.

Wa salamu Alaykum!

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Jazak Allaho kheiren my brother @Hiyaro 
Good job from your side.

**Comment by Muslim629** [comment]
@ahmedre 

السلام عليكم و رحمة الله و بركاته اخي الكريم 
Why you don't get New Warsh version? AI format from Qur'an complex is good and new 2020?

**Comment by Muslim629** [comment]
@ahmedre 

السلام عليكم و رحمة الله و بركاته 

My brother can you send me in my gmail your number, because i'm not very active in github and gmail : samirnurshaba@gmail.com

**Comment by Muslim629** [comment]
> wa3laikum alsalam wa ra7matullah -
> good news - al7amdulillah i got the King Fahd pages and am preparing them.
> https://epub.qurancomplex.gov.sa/issues/qiraat/warsh39/offline/download.pdf
> walsalam 3alaikum.

السلام عليكم و رحمة الله و بركاته 

Why when i zoom pages lost quality, download pdf file?

**Comment by Muslim629** [comment]
> > wa3laikum alsalam wa ra7matullah -
> > good news - al7amdulillah i got the King Fahd pages and am preparing them.
> > https://epub.qurancomplex.gov.sa/issues/qiraat/warsh39/offline/download.pdf
> > walsalam 3alaikum.
> 
> السلام عليكم و رحمة الله و بركاته
> 
> Why when i zoom pages lost quality, downloaded pdf file?

Who are you sorry, because i can't see your name mention in comment

**Comment by Muslim629** [comment]
السلام عليكم و رحمة الله و بركاته 
@ahmedre 
@AhmedKamal 
Do you want this Nastaleeq Mus'haf?
Is HD
![Screenshot_20201110-074217_Adobe Acrobat](https://user-images.githubusercontent.com/52772116/98641096-819c4480-232b-11eb-8764-b1196743efc6.jpg)
 quality vector art.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
sure brother, would be happy to have it - we already have a naskh mushaf so might not replace ours but if this one is newer (and if it's the King Fahd one especially) would probably consider replacing it.

not sure why the warsh pdf loses quality so much when zoomed in.
sure, will email you in sha' Allah.
والسلام عليكم

**Comment by Muslim629** [comment]
> وعليكم السلام ورحمة الله وبركاته
> sure brother, would be happy to have it - we already have a naskh mushaf so might not replace ours but if this one is newer (and if it's the King Fahd one especially) would probably consider replacing it.
> 
> not sure why the warsh pdf loses quality so much when zoomed in.
> sure, will email you in sha' Allah.
> والسلام عليكم

If i shared with you link, you will use in app or no?

**Comment by Nelnaji** [comment]
A salamu Alaykum @ahmedre 

Is it still necessary for me to work on this table?
https://docs.google.com/spreadsheets/d/1N_ENxcVUn29S2CrPSCN17WWs52kAZIcQNu0Kgps07zo/edit?usp=sharing

I went back into completing it but I just checked that the app was working fine.
tell me if there's anything for me to do to contribute to the project.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
no, this is done and has been released to production now.
jazakumAllah khairan.
walsalam 3alaikum

**Comment by Nelnaji** [comment]
You've done a fantastic job, may Allah swt bless you and the people who have helped you aswell!

**Comment by ahmedre** [comment]
ameen, most of it was done by other brothers here, may Allah accept and reward all of us - ameen
