### ISSUE TITLE
Ayah highlight 

### ISSUE THREAD

**Issue by Baha2Odeh** [quran/quran_android#1364]
Aslam alykom,
This is not bug
But i need to understand how does the highlight part of quran image is working while its an image

Could anyone explain it and how to use it

**Comment by murtraja** [comment]
Wa alaikum as Salam,
I will not be able to help you completely, but can provide some pointers which you can refer to help yourself.

1. You are right, the pages are all images
2. Each image is made up of 15 lines, each image is made up of ayahs. Each ayah is made up of words which we call glyphs
3. We have the rectangle coordinates of the glyphs relative to the page.
4. We know how many glyphs make up the ayah and in what order and in which lines.
5. The highlighting view is simply a canvas overlaid on top of the image, because the highlighting color has a non 100% opacity value, it looks like a highlight, but really it is just a translucent rectangle.
6. Each ayah highlight is made up of at most 3 rectangles - the no. of rectangles depend on the type of ayah (single line, multi-line, etc.)
7. There is a function [normalizeAyahBounds](https://github.com/quran/quran_android/blob/e015f9a57db44e0f3ce9a05b54a94590a485efc8/app/src/main/java/com/quran/labs/androidquran/model/quran/CoordinatesModel.java#L72) which converts the rectangles of the glyphs to actual highlighting rectangles.
8. Also, there are multiple highlights for a particular ayah - bookmark highlight, playback highlight, notes highlight, selection highlight. Which highlight gets shown depends on their priority. [Here](https://github.com/quran/quran_android/blob/15438c918e6122c7584091bf012621c19fc628b0/app/src/main/java/com/quran/labs/androidquran/widgets/HighlightingImageView.java#L137).
9. Lastly, you might be interested in [this](https://github.com/murtraja/quran-android-images-helper) which reproduces the algorithm in Javascript
10. Also, you can look at this [PR](https://github.com/quran/quran_android/pull/1313) and [this](https://github.com/quran/quran_android/issues/951) issue to understand the relevant part of code base

**Comment by Baha2Odeh** [comment]
> Wa alaikum as Salam,
> I will not be able to help you completely, but can provide some pointers which you can refer to help yourself.
> 
> 1. You are right, the pages are all images
> 2. Each image is made up of 15 lines, each image is made up of ayahs. Each ayah is made up of words which we call glyphs
> 3. We have the rectangle coordinates of the glyphs relative to the page.
> 4. We know how many glyphs make up the ayah and in what order and in which lines.
> 5. The highlighting view is simply a canvas overlaid on top of the image, because the highlighting color has a non 100% opacity value, it looks like a highlight, but really it is just a translucent rectangle.
> 6. Each ayah highlight is made up of at most 3 rectangles - the no. of rectangles depend on the type of ayah (single line, multi-line, etc.)
> 7. There is a function [normalizeAyahBounds](https://github.com/quran/quran_android/blob/e015f9a57db44e0f3ce9a05b54a94590a485efc8/app/src/main/java/com/quran/labs/androidquran/model/quran/CoordinatesModel.java#L72) which converts the rectangles of the glyphs to actual highlighting rectangles.
> 8. Also, there are multiple highlights for a particular ayah - bookmark highlight, playback highlight, notes highlight, selection highlight. Which highlight gets shown depends on their priority. [Here](https://github.com/quran/quran_android/blob/15438c918e6122c7584091bf012621c19fc628b0/app/src/main/java/com/quran/labs/androidquran/widgets/HighlightingImageView.java#L137).
> 9. Lastly, you might be interested in [this](https://github.com/murtraja/quran-android-images-helper) which reproduces the algorithm in Javascript
> 10. Also, you can look at this [PR](https://github.com/quran/quran_android/pull/1313) and [this](https://github.com/quran/quran_android/issues/951) issue to understand the relevant part of code base

Thank You very much

**Comment by rizerzero** [comment]
I'm Also trying to understand how this works (currently writing a flutter app), if any developer here is interested in a freelancing mission to help me with that, it would be wonderful.
Jazaakoum Allah khaira.
