### ISSUE TITLE
Issue when playing audio in one page with tow Sorahs

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1376]
Salam 3alikom 
We can't play audio from page contains  tow surahs, only when we download both Surahs
Ex: Ala3la n: 87 الأعلى  and Elghashia n: 88 الغاشية
If we haven't 88 we can't play 87. Whatever  the reciter (offline mode).

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته

This is if you have selected `page` mode in `Settings -> Download amount`.
If you choose `Surahs` mode, it will download up to Surah 114 before playing! I guess [this pr](https://github.com/quran/quran_android/pull/1386) introduced the issue. Because now [pageLastSura](https://github.com/quran/quran_android/blob/428948a2b79d692e61f64fec395e437461adef2d/app/src/main/java/com/quran/labs/androidquran/util/AudioUtils.kt#L122) is never changed to the number of the next Surah.

Anyway, I don't know why is this `Download amount` option (which shows: Preferred download amount for _non-gapless_ audio) is interfering with gapless files. I guess a better approach is:
1. If the file of a gapless audio is available, just play it. 
2. If many consecutive gapless files are available, play them all.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً
opened a PR which should fix this - the default behavior is what you mentioned (playing the file if available and continue until the next file is no longer available). there are 2 reasons - first, as you mentioned, I broke it with that PR that you linked.

secondly, even before that, there was logic that says "if the sura ends in the middle of the page, play until the end of the sura ending on that page." In other words, if you consider playing sura Waqi3a, because it ends in the middle of the page, it would make the range through the end of sura Hadeed.

i've removed this logic now and just make the required range play until the end of the current sura.

جزاكم الله خيراً
والسلام عليكم
