### ISSUE TITLE
Saving application directory 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1478]
السلام عليكم ورحمة الله وبركاته 
@ahmedre jazak Allaho kheiren 
I have an issue while changing the saving directory of application v 3.0.2 , I choose the main directory 
but the app return to: /storage/emulated/0/ 
Android/data/com.quran.la 
bs.androidquran/files
This issue only with Android v 10 ( note 10+) but with Android 9 no issue.
والسلام عليكم ورحمة الله 
![Screenshot_20201030-134739_Quran](https://user-images.githubusercontent.com/60948528/97699106-a6d2bc80-1aba-11eb-9a9f-e4d4d2ec95aa.jpg)

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I got this comment from google play store
![Uploading Screenshot_20201104-061533_Google Play Store.jpg…]()
@ahmedre please try to fix this issue 
وجزاك الله خيرا

**Comment by ahmedre** [comment]
wa3laikum alsalam -
this is actually intentional - so on Android 29 and above, scoped storage is a thing, and they don't want people storing data on the /sdcard root. the app then copies the data for anyone on Android 29 or above to the internal storage directory. once we target Android 30 (Google will require this next year), we will lose the ability to write to /sdcard/quran_android for all new installs or to get external storage permission to it, and the recommendation is to write in the app specific directory.

while the upgrade case will still work (i.e. if you're using the app on Android 29 and upgrade to Android 30, everything will continue to work), it won't work for new installations. in preparation, i've been migrating the data. if this causes too much trouble i can only do the migration for Android 30 and above.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
thinking to make some changes -
1. only do this on Android 30 and above,
2. add some documentation as to why this happens,
3. remove the setting to copy to the /sdcard root in advanced preferences on Android 30 and above

**Comment by benomaire** [comment]
Is this complaint related? Can we use Mediastore for audio?

>  Avec la mise à jour du 30 octobre 2020, les téléchargements audio s'effacent dès qu'on cesse d'utiliser l'application pendant quelques heures. Ce problème n'est apparu qu'avec cette mise à jour. ???


Also I suggest at least asking users before moving files from external memory (those users deliberately chose external storage). I guess some may not upgrade to Android 30 soon. 
Users of Today don't care what Google decides to do Tomorrow. They think we got a bug!

I appreciate that you want to make the transition smooth but, for some it is not!

**Comment by ahmedre** [comment]
i don't want to use MediaStore because it's hard to do something everyone is ok with - some people will complain if we copy the files among their audio files, but some people will also complain if we don't. doing both and making it an option doesn't seem like the right solution here honestly. i've seen other Quran apps that just use the Google directory and don't see complaints in their reviews about it. also, if you think about it, all iOS apps work that way (all files are removed when the app is uninstalled).

for now though, since as you mentioned some people may not upgrade to Android 30 soon, I can make this enabled from Android 30 instead of from Android 29 and display a message (along with blocking the option to go back in the settings if someone is already on Android 30).
