### ISSUE TITLE
Bug: latest version

### ISSUE THREAD

**Issue by Bakr-Ali** [quran/quran_android#1481]
Alsalam alaikum,
“There is a bug in the latest update, if i choose the data to be on sd card, when the application starts it move the data into the internal storage automatically -nearly 3 GB moved- and if i try to change storage place from setting to sd card, it moves, but when i open the app next time the same problem appear and this made my phone crash many times, i hope u will fix this bug the next update.”
Copied from a recent review after i had the same bug.
Version 3.0.2

**Comment by ozbek** [comment]
Wa alaikum assalam.

Would you kindly provide your phone details, please (model name, Android version, etc)?

**Comment by ahmedre** [comment]
wa3laikum alsalam -
this is actually intentional - so on Android 29 and above, scoped storage is a thing, and they don't want people storing data on the /sdcard root. the app then copies the data for anyone on Android 29 or above to the internal storage directory. once we target Android 30 (Google will require this next year), we will lose the ability to write to /sdcard/quran_android for all new installs or to get external storage permission to it, and the recommendation is to write in the app specific directory.

while the upgrade case will still work (i.e. if you're using the app on Android 29 and upgrade to Android 30, everything will continue to work), it won't work for new installations. in preparation, i've been migrating the data. if this causes too much trouble i can only do the migration for Android 30 and above.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
let's resume this discussion in #1478
