### ISSUE TITLE
A playback bug in the latest update

### ISSUE THREAD

**Issue by ahmed3110c** [quran/quran_android#1482]
In the latest update when i select "Only play the above verses" when i want to play a Sura, at the end of the Sura, "بسم الله الرحمن الرحيم" sentence is played again and the last Ayah is being repeated and the playback doesn't stop automatically till i press stop. Please fix this bug.

**Comment by ahmedre** [comment]
jazakumAllah khairan for reporting - i will try to repro this tonight in sha' Allah - in the meanwhile, can you give me some more details - if you can send a video would really help but if not, can you give me specific examples to make it easy for me to repro this? jazakumAllah khairan

**Comment by ahmed3110c** [comment]
Here is an example in this video about this bug

**Comment by ahmed3110c** [comment]
Here is an example in this video about this bug

**Comment by ahmed3110c** [comment]
Here is an example in this video about this bug.

http://www.mediafire.com/file/gtwkjqjseegua5v/20201104_120340.mp4/file

**Comment by ahmed3110c** [comment]
I also want to thank you for adding more recitations. I hope you can add Sheikh Ahmed Mohamed Aamer in the next updates and please bring back playback settings option when i select an Ayah and press play on it.

**Comment by ahmedre** [comment]
jazakumAllah khairan - downloaded the video - will look into figuring this out in sha' Allah.

**Comment by benomaire** [comment]
Apparently caused by [this](https://github.com/quran/quran_android/commit/a53d58d8010b3e53fb263abf7c12b30d7566e15a)!

**Comment by ahmedre** [comment]
@benomaire yes, but that just exposed the bug that was already there. with timing files, there's an optional "ayah number 999" entry that can be there to skip audio at the end of the ayah - for example, if the audio file ends with "sadaqa Allah al 3azeem," adding a 999 entry can make the audio file stop before saying "sadaqa Allah al 3azeem" without actually cutting the extra audio out of the file.

the fix you mentioned fixed a case where those 999 files exist but the highlighted ayah wasn't updated - adding the line to cause it to update uncovered a hidden older bug - if a 999 entry existed and we reached it, we should stop audio playback, but we weren't. it was working before because without "refreshing," the file would end, which would cause us to understand that we reached the end of the playback, and then stop.

will push a PR to fix this shortly in sha' Allah.
