### ISSUE TITLE
QuranDataSource: Extract data from Ayah info database

### ISSUE THREAD

**Issue by AbdullahM0hamed** [quran/quran_android#1494]
Seeing as how the future of the app seems to be a single, unified app with multiple masahif - it would be a good idea to get the data in QuranDataSource from the ayah info database instead of hardcoding the values into the app.

The info provided by the methods in https://github.com/quran/quran_android/blob/9df9ac5c592c50eac7fb3eec13726f498eaa1582/common/data/src/main/java/com/quran/data/source/QuranDataSource.kt#L4-L7 and https://github.com/quran/quran_android/blob/9df9ac5c592c50eac7fb3eec13726f498eaa1582/common/data/src/main/java/com/quran/data/source/QuranDataSource.kt#L10 can all be extracted from the ayah info database. 

Here are the raw SQL queries I've tested and the method they provide the same information as:

• getNumberOfPages -> "select count(distinct page_number) from glyphs"
• getPageForSuraArray -> "select page_number from glyphs group by sura_number"
• getSuraForPageArray -> "select sura_number from glyphs group by page_number"
• getAyahForPageArray -> "select ayah_number from glyphs group by page_number"
• getNumberOfAyahsForSuraArray -> "select max(ayah_number) from glyphs group by sura_number" 

I assume all interaction with the ayah info database should be done via [AyahInfoDatabaseProvider.java](https://github.com/quran/quran_android/blob/685b8477ddf711d388e0543fe406cc55004b0900/app/src/main/java/com/quran/labs/androidquran/data/AyahInfoDatabaseProvider.java) and [AyahInfoDatabaseHandler.java](https://github.com/quran/quran_android/blob/685b8477ddf711d388e0543fe406cc55004b0900/app/src/main/java/com/quran/labs/androidquran/data/AyahInfoDatabaseHandler.java), but I've noticed that there will be issues importing that into classes inheriting QuranDataSource (I assume due to QuranDataSource being part of a library and not having access to app code)

**Comment by ahmedre** [comment]
wa3laikum alsalam,
the reason `QuranDataSource` is an interface is precisely so i can swap out implementations at compile or run time. i don't want to make this use an actual database because most of these calls happen on the ui thread and delaying them would greatly affect the app speed. today, `Warsh`, `Qaloon`, and `Naskh` override whatever they need to from these to make their data available properly.

`QuranDataSource` isn't part of `app` directly - it's part of the `common:data` library. consequently, `app` and other libraries can easily use it (as long as there are no circular dependencies).
walsalam 3alaikum.

**Comment by ahmedre** [comment]
jazakumAllah khairan akhi for the suggestion though, barak Allah feekum!
