### ISSUE TITLE
Fix infinite download loop

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1499]
The complaints keep popping up. This is probably related to latest storage updates. I cannot regenerate this bug though. 
One idea is to keep a counter and if it downloads files two times in a very short period (a day or two), it goes back to /sdcard.

Now these people are losing their files _many_ times! Instead of _one_ time if we lose access to files next year. I think some big messaging apps are still using /sdcard.

A recent comment:

> aaal Dawud
November 22, 2020
Used to like the app but the latest update version ruined it all.just can't understand why files have to be redownloaded or app can't be accessed offline.just to note I have been a regular user for almost six years.

Another one with 47 upvotes

> Apsari Anindita Nugroho Putri
November 15, 2020
Assalamualaikum warahmatullah wabarakatuh. Very beneficial app. But after the latest update, everyday the app keep asking to re-download the ayah and translation over and over, while the setting for app permission already allow to access the storage. Please kindly to fix it. Jazaakumullahu khairan. BarakAllah fiik.

**Comment by ahmedre** [comment]
a lot of people email me about this - i always tell them to tell their cache cleaning app to remove "Quran" from the list and it helps for most of them - but to be honest we used to get this before the changes also (though less than we do today).

was actually thinking to default to internal storage (where people and apps can't easily reach) for these people maybe but not sure  ¯\_(ツ)_/¯

**Comment by benomaire** [comment]
I think I found the error:
if (a) is the special folder `Android/data/...'
(b) is the root of internal storage

Try the following: 
1. go to settings -> Advanced Options -> Quran data directory.
2. If your files are in (a), choose (b). And vice versa.
3. If your files take a lot of space >1GB, and the screen turns off before the app moves the files to the new location, then it will never finish moving even after hours. Never!
4. Now `kill' the app (swipe it out from the open apps list).
5. Open the app again, and it will prompt you to download the files.
6. Choose No, and verify that the files are on disk in either (a) or (b) but the app does not see them.
7. Repeat 1.
8. Choose the folder that contains the files (as found in 6.)
9. Now the app sees the files again!

I suggest one of the following:
1. (my preference) Never move files automatically unless the user does so by going to Advanced Options. Default new installations to (a) and keep using (b) for people who have it.
2. If turning off the screen (manually or auto) is the issue. Make sure to keep it on.

AFAIK, this is not related to cleaning apps. And this could be an old bug related to copying files. People previously (before the recent 2 updates) reported the app losing access to files on upgrade if the files are on external storage.

One more thing, If @nacer80 agrees to test new releases, I suggest releasing updates on Google play 1 or 2 days after releasing them here on github. I think He is good at testing.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
so this is a separate bug and should be fixed, but it's different than what people are complaining about. most of those people don't try to change the path where the Quran app is and just use the defaults. i found that certain device types (Xiaomi, Oppo, etc) have built in cache cleaning support in the OS that is very aggressive and treats files in `/Android/data/<package>` as something they erase by default. everyone who complained so far and i asked them to disable this told me it solved the problem. i checked Huawei, Google, and Samsung phones and all their built in cleaning tools do the right thing.

in the latest version, i only copy files automatically for people on Android 11 (see [here](https://github.com/quran/quran_android/blob/77f6f791b589bef83c39c0c4b0941273e6bec514/app/src/main/java/com/quran/labs/androidquran/QuranDataActivity.kt#L197)). Android 11 only accounts for a tiny percentage of people today.

so 1 is already done (except for api 30 where i have no choice since fresh installs won't be able to write to /sdcard anyway). but 2 we can do in sha' Allah, but it won't fix the major issue people are complaining on.

sure, no worries pushing betas first for brother Nacer to test if he's willing to in sha' Allah.
walsalam 3alaikum.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Jazakoum Allah kheiren my brothers for your hard job.
I agree with you
بارك الله فيكم

**Comment by benomaire** [comment]
>  i found that certain device types (Xiaomi, Oppo, etc) have built in cache cleaning support in the OS that is very aggressive and treats files in `/Android/data/<package>` as something they erase by default. everyone who complained so far and i asked them to disable this told me it solved the problem. 

So I was wrong. I never thought that some devices do such a thing! Especially that Google is pushing to store files there!


> in the latest version, i only copy files automatically for people on Android 11 (see [here](https://github.com/quran/quran_android/blob/77f6f791b589bef83c39c0c4b0941273e6bec514/app/src/main/java/com/quran/labs/androidquran/QuranDataActivity.kt#L197)). Android 11 only accounts for a tiny percentage of people today.

Sorry for not reading the code carefully, but it is good to get a confirmation from you.

جزاكم الله خيرا

**Comment by benomaire** [comment]
Another suggestion, although this might confuse new users:
Change the `downloadPrompt` string to include this at the end: 
(If the files disappear repeatedly then disable your cache cleaner or ask it not to erase Quran's files.)

**Comment by ahmedre** [comment]
i've made some changes in #1511 - by switching to internal storage by default, third party cache cleaning apps can't remove files (unless the person is root). it's also very unlikely that the OS itself will remove files from there, since otherwise, apps with sign in, etc will always get signed out and lose their data.

i've made a small change to keep the screen on in the advanced prefs screen with should also prevent sleeping during the moving of files. let's hope this helps in sha' Allah.

there's one last edge case i am still thinking about - the documentation for both `getFilesDir` (internal storage) and `getExternalFilesDir` (external storage where we are allowed to write) both say:

> The returned path may change over time if

for external storage:
> different shared storage media is inserted, so only relative paths should be persisted.

for internal storage:
> the calling app is moved to an adopted storage device, so only relative paths should be persisted.

this isn't something we're handling at the moment and should.

**Comment by ahmedre** [comment]
i've added some logging to also check for this case, though i really doubt it will happen much (if at all).

al7amdulillah i have a good feeling that moving to internal directory will fix these issues, because looking back at some of the logs from whenever we detected lost files, in a lot of cases when the data went away, a test file in internal directory did survive. so Allah-ul-musta3an hoping this fixes things in sha' Allah.

**Comment by ahmedre** [comment]
merged, so closing this for now - jazakumAllah khairan.
