### ISSUE TITLE
add ability to increase playback speed of quran 

### ISSUE THREAD

**Issue by MahmoudMabrok** [quran/quran_android#1529]
i did it, i will make PR ISA

**Comment by benomaire** [comment]
I used to wish we have this feature. But if you think about it, missing this feature is probably the better choice. Some reasons are:
1. I don't think going over Quran **fast** is *an objective*. For example, refer to Tafseer of 7:204, 17:106, 25:32, 73:4, and 75:16.
2. I am afraid if people get used to the fast speed, they cannot listen to the true speed anymore.
3. I don't know of any reputable radio broadcast that aired fast-forwarded Quran audio (not even casual human speech AFAIK).
4. Reciters (Qaris) spend years on end learning Quran Tarteel and Tajweed, and recordings take at least a month (if recorded in Ramadhan for example), and studio recordings are extensively reviewed. All these efforts would be in vain if people speed up and loose the chance of learning correct Tajweed, feeling the meanings, etc.
5. If someone wants to memorize fast, then you know the companions of prophet Mohammad Peace be upon him used to go 10 verses at a time, memorizing and learning at the same time. Hopefully, if you pass away before finishing, your reward is saved because you were on the path. إن شاء الله
6. Different reciters with different *natural* speeds are available.
7. sorry to mention this analogy but I think people listening to music don't speed it up.

I know there are arguments about reading Quran in like 3 days. But I don't think this is the norm or recommendation. I also know people speed up using other means, but with the app we share responsibility as well, so I think better safe than sorry.
What do you think? 
Should we add more Taraweeh recitations (for haramain, that will not be a single qari)?
جزاكم الله خيرا

**Comment by ahmedre** [comment]
well said @benomaire, jazakumAllah khairan - lots of people requested this over time, but never entertained it for many of the reasons you mentioned, and don't want to - i don't mind adding a "7adr" mus7af recitation where the reciter in general reads with a natural quick voice (or more tarweeh type recordings).

**Comment by MahmoudMabrok** [comment]
Thanks for this discussion, I added it as i had a "جلقة تحفيظ"  and i was need to listen ayahs in speed so i can re-memorize my recitation, i will need this option only before go to shekh (الشيخ).

**Comment by amynbe** [comment]
Not that I need this feature (I'm more of a visual learner, listening doesn't help my memory as much), but just to explore more options:
- A possibility would be to hide this feature behind a setting labelled "Advanced player interface".
- A warning could further discourage the user from enabling the option.
- Or, add a "save audio file to the phone" feature so the user can open it in an external player.

Other points, in favour of the features:

- I don't believe in the argument that people can't listen to slow pace once they get used to fast one. I listen to podcasts in accelerated fashion, and have no problem going back to normal speed.

- Technology has to adapt to users, not the other way around. Fast playing exists since cassette players such as Walkmans, and external android/desktop players/youtube can do that too. I'm not sure we're at the point where we need a fatwa to decide if this kind of features is acceptable in a Quran application. If so, then let's ask a scholar.

- Although for 99% of cases, this feature has nothing to do in a Quran app (as opposed to e.g podcasts where "saving" time makes sense), I can understand the point of a student who wants to help keep focus before a large recitation to his teacher.

**Comment by ahmedre** [comment]
while some of these are good arguments, I don't want to do it because I don't want it to be used to disrespect the Quran. that having been said, in the next version, I've added a Hadr recitation which is very very fast recitation specifically intended for revision purposes.

closing this.

**Comment by ahmedre** [comment]
we implemented this after @mohamede1945 suggested a good respectful way to do it. here's a [fatwa](https://www.islamweb.net/ar/fatwa/129310/%D8%AD%D9%83%D9%85-%D8%AA%D8%B3%D8%B1%D9%8A%D8%B9-%D8%B5%D9%88%D8%AA-%D8%A7%D9%84%D8%AA%D9%84%D8%A7%D9%88%D8%A9) saying that this is okay.
