### ISSUE TITLE
Change Surahs name in Surah list and in page header 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1739]
السلام عليكم ورحمة الله وبركاته 
I hope we change the Surah names format in Surahs list and page header specially Arabic language (with Tashkil as real Mushaf)to new format as the table attached : [Surahs_names](https://drive.google.com/file/d/12hMJfqhlbd6o9Ekmi8co9-lPwwmBNlOb/view?usp=drivesdk)  

سُورَةُ الفَاتِحَةِ Al-Fâtihah AL-FÃTIHAH
سُورَةُ آلِ عِمۡرَانَ Âl-`Imrân ÃL-`IMRÃN

وجزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً
downloaded the file

**Comment by benomaire** [comment]
# English
The proposed names match [publication images](https://publications-img.qurancomplex.gov.sa/?p=44&mushaf_pageno=794&imagewidth=550) except the following:
- Tâ-hâ
- Ash-Shûrâ
- Al-Mujâdalah
- Al-Mumtahinah
- Al-Layl
- Al-Bayyinah
- Quraysh
- Al-Kawthar

However, if we compare with the latest version of KFGQPC or [Noor International](https://www.noorinternational.net/en/translation/swarlist), we find more differences. For example, both KFGQPC and Noor International use an H with a dot below to represent ح.

# French
The proposed names does not match [publication images](https://publications-img.qurancomplex.gov.sa/?p=48&mushaf_pageno=13&imagewidth=550) nor [Noor International](https://www.noorinternational.net/fr/translation/swarlist).
For example:
1. Only the proposed names use tilde above letters, e.g. Ã. Others use Ā or Â.
2. KFGQPC uses ᶜ, Ţ, Ş, H̲ whereas NOOR uses ‘, TH, Ç, KH for ع, ث, ص, خ. etc.
3. KFGQPC uses a single Latin letter for each Arabic letter.

## Capitalization
I don't think that capitalization is necessary because the same pdf of KFGQPC does not capitalize all letters in headers. See [publication images](https://publications-img.qurancomplex.gov.sa/?p=48&mushaf_pageno=13&imagewidth=550). However, the pdfs of [Rachid Maach](https://islamhouse.com/fr/books/2831133/) and [Noor International](https://islamhouse.com/fr/books/2830489/) use capital letters.

# Summary
I don't have a strong opinion yet. But I think we need to identify the source we are using. I mean, it could be
1. a specific print by KFGQPC
2. the latest print by KFGQPC
3. the latest print by Noor International
4. etc

So my question to Brother @nacer80, what is your source?

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله 
 
The source is from great quran app.
1-About capitalization, I agree with you. It is not necessary.
2- No big difference between Ã ,Ā and Â.
3 - In Franch language rarly  persons  use ᶜ, Ţ, Ş, H̲.

وجزاك الله خيرا

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته

And what is the source of Great Quran app?

(2) It could be better to choose something that is used by the French translations in quran_android. Also, I failed to find the tilde used in any pdf (if you know any, please share), and that's why I feel it may not be the optimal choice.

(3) I agree. This is also true in English BTW. But I think the use of some extra characters by experienced organizations cannot be ignored. We may consider adding the mapping of these "extra characters" to Arabic letters in the "Help" page of quran_android (although that might not be so useful for people not studying Arabic).

# Other notes
These are more notes related to Great Quran app
## English
BTW, the English Sura names proposed here does not fully match Great Quran app (version 5.5.1) like:
- Al-`Imrân
- An-Nisâ
- Al-Mâidah

![en](https://user-images.githubusercontent.com/69304392/140571145-168a1959-5f77-4b03-8cd8-5897da44e53a.png)

Am I missing something?

## French
Great quran app is currently using the French translation of Noor International. Hence, I am not sure why they are not using the Sura names of Noor International as well.

# Summary
Again, this topic is somewhat subjective, and I am trying to reach some guidelines that can be applied to other languages as well, since this is not the first update for sura_names.

جزاكم الله خيرا

**Comment by ahmedre** [comment]
should we just take the names from King Fahd publication images (at least for English since we're so close except for the handful of suras that don't match?) for French, I don't speak the language so will leave it to you two to tell me what you think is best, but would be nice if we can point to a source (King Fahd or Noor International) instead of another app.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله 
Brothers @benomaire @ahmedre 

In this update
I got the Surah index update from [Noor International](https://noorinternational.net/ar/translation/swarlist)
I created tow files uppercase and  lowercase.
[Sura_names_Franch_lowercase_update.txt](https://github.com/quran/quran_android/files/7490179/Sura_names_Franch_lowercase_update.txt)
[Sura_names_Franch_last_update.txt](https://github.com/quran/quran_android/files/7490180/Sura_names_Franch_last_update.txt)
But I still prefer the old one (the list sent before)
Because in the new index they used " û " instead of " ou " and " Ç " instead of " S "  "ص"...
Also Noor International developed an app and they used old ones.

![Screenshot_20211106-103137_Noor International Quran.jpg](https://user-images.githubusercontent.com/60948528/140605196-f9e9064f-ddde-4eaf-abd1-1097553da11a.jpg)


وجزاكم الله خيرا

**Comment by benomaire** [comment]
@nacer80 You seem more knowledgable than me on this topic, and my apologies if my second post caused any misunderstanding.

So If I understand correctly, the merged list is the old version of Noor International for French Sura names (so we can only update capitalization).

Now it remains to decide on English Sura names. Is the merged list also the old version of Noor International? Or should we modify it to match KFGQPC publication images?

جزاكم الله خيرا
