### ISSUE TITLE
Para 7 Toast

### ISSUE THREAD

**Issue by aghand0ur** [quran/quran_android#1781]
The toast of Para 7 appears one page ahead of expected one..is it a bug? shall I fix it?

**Comment by ahmedre** [comment]
This is intentional. Juz' 7 and Juz' 11 often get us emails because in the King Fahd Mushaf, the label on the top of the page changes on the next page (because the vast majority of the page is on the previous juz'). For both the index and the toast, however, we show it on the earlier page because that's literally where the marker is.

**Comment by aghand0ur** [comment]
Thank u @ahmedre.
It would be great to go through open issues and close those with no pending follow-ups.
