### ISSUE TITLE
Missing reciters in android app

### ISSUE THREAD

**Issue by Rafsanjani** [quran/quran_android#1969]
I installed the iPad app from the app store and could see at least 100 reciters in the audio manager but I can only see 3 of them in the android app. Is there something I am missing?

**Comment by ahmedre** [comment]
the open source code only has 3 reciters. the full app in the store has the full list.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله 
Here You will find the full app:
https://play.google.com/store/apps/details?id=com.quran.labs.androidquran

**Comment by Rafsanjani** [comment]
Oh alright, that makes sense then. Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mustafakhalaf-git** [comment]
> the open source code only has 3 reciters. the full app in the store has the full list.

Can I know why?

**Comment by ahmedre** [comment]
lots of people are forking the project, adding ads on top, and re-publishing it as is. this is disrespectful to the book of Allah, and also gets us many angry emails of people making du3a against us for disrespecting the book of Allah, because those who published the project left our email for support (not to mention are using our serves for audio and data). in order to protect the project without closing it from open source completely, we've chosen to limit parts of the project to the app store version only. while this won't stop people from doing this in the future, it will make it a lot more work, and thus hopefully discourage them from doing it.

**Comment by mustafakhalaf-git** [comment]
> lots of people are forking the project, adding ads on top, and re-publishing it as is. this is disrespectful to the book of Allah, and also gets us many angry emails of people making du3a against us for disrespecting the book of Allah, because those who published the project left our email for support (not to mention are using our serves for audio and data). in order to protect the project without closing it from open source completely, we've chosen to limit parts of the project to the app store version only. while this won't stop people from doing this in the future, it will make it a lot more work, and thus hopefully discourage them from doing it.

Ah I see, JazakAllah this is a good choice

I noticed the reciter thing when I wanted to make a custom color palette for the app, then after building I didn't see afasy or any other reciter, I guess I can just put the quranicaudio link for afasy in the kotlin files for now
