### ISSUE TITLE
Clarify Anti-Features that fdroid show?

### ISSUE THREAD

**Issue by not-programmer98** [quran/quran_android#2228]
I hope you clarify these Anti-Features:
    NonFreeDep
    NonFreeNet
    Tracking
What are you using cause fdroid to flag you with this?

**Comment by ahmedre** [comment]
I think we have Firebase Crashlytics for crash reporting - if I had to guess, that's the only thing that meets the tracking requirement (because for analytics and crashes, it gathers a unique id). If you have more information happy to revisit.

**Comment by RohanRahman-s** [comment]
• Has non-free dependencies.
• Promotes non-free network services.
• Tracks or reports your activity.

According to droid-ify. Looks kind of bad on the FOSS standard.

**Comment by ahmedre** [comment]
yeah this is only due to Firebase. Not sure what "promotes non-free network services" means though. "tracks" is a strong word since Firebase doesn't tell me "person x in place y did a, b, c" - it just aggregates analytics about x people clicked this button, y people launched the app, etc.

**Comment by ahmedre** [comment]
actually, checking [here](https://gitlab.com/fdroid/fdroiddata/-/commit/61ff4335559260c7d809b90a1feffa4bc01cf3cd), I remember I gave them a way to build without Firebase, which they do. If someone has more information on this happy to help resolve. Rethinking about it, I am guessing the "non-free dependencies" is due to the fact that a small amount of our code is closed to make it a bit more difficult for people to duplicate the app and add ads to it. Even then, the app doesn't compile with them, so not sure.

**Comment by ahmedre** [comment]
update - let's continue this discussion in #755 which has more background.
