### ISSUE TITLE
Translation in french is not correct

### ISSUE THREAD

**Issue by Maximus203** [quran/quran_android#2471]
Hello, please correct this error. Instead of "Mediation" this is "Meditation":
![Screenshot_20231129-111102](https://github.com/quran/quran_android/assets/64066992/fcf18e7d-3193-47c5-8672-70e4b9cbf29f)

**Comment by ahmedre** [comment]
salam 3alaikum,
our French translation for Hameedullah comes from Quranenc, and I've filed your request to them here - https://quranenc.com/en/browse/french_hameedullah/54/40 - once they fix we can import the updated version. Closing for now on our end since there is nothing more for us to do at the moment.
walsalam 3alaikum.
