### ISSUE TITLE
Arabic text in translation

### ISSUE THREAD

**Issue by stankovski** [quran/quran_android#266]
ASA,

The Arabic text in translation has a common bug (?) where all hamza with fatha followed by alif are stored in sqlite database to alif with madd. Example surah Taha ayah 114 - word quraan.

JAK,
Denis S.

**Comment by ahmedre** [comment]
sorry for not updating this in ages, but i checked and this is ok - it's basically because the arabic (in quran.ar.db) is imlaei arabic (the written style of arabic that you'd write today), whereas the images are uthmani style. hence often times, words maybe spelled differently between the two views.
