### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fahad-alkamli** [quran/quran_android#2778]
I am working on extracting x and y Coordinates for each ayah location  and I was wondering if you guys are doing it manually? or using some sort of AI?
The reason I ask is  I am planning to do my Master's degree thesis on extracting the Coordinates automatically.
Thank you for all the hard work.

**Comment by ahmedre** [comment]
no, it's not manual. for the 1405 pages, the fonts gave us the details on which words were in each ayah, which allowed us to draw and get the width of each ayah and know the x, y coordinates that way. for the other pages, we have https://github.com/quran/ayah-detection which uses some Python scripts to find the ayah markers and we use that to identify where the coordinates are.

jazakumAllah khairan.

**Comment by Fahad-alkamli** [comment]
As lam alykum , just to follow on my project , I have released it on github for people to use please feel free to check it out and give me feed back.
It's Surah and Ayah detection tool written in java that is based on openCv template matching.
It focuses on having multiple templates for a robots detection and it also includes different resources that may be helpful for people needing this feature in their own app "click to detect ayah based on Y and X coordinates" .
The project  include java documentation for each method and each class but I will also update them frequently .
May Allah reward us for this.
https://github.com/Fahad-alkamli/extract-ayah-using-opencv/

**Comment by ahmedre** [comment]
wa3laikum alsalam,
happy to hear you got it working masha'Allah - multiple templates is definitely useful since the shapes of ayat can change slightly in some pages.

I'd imagine a more common use case would be to run this once, extract a database, and ship it with the app, since a dependency of OpenCV in a mobile app is a big dependency, especially when the data can be prepared with your program or the ayah-detection repo offline first and then bundled as a database.

May Allah reward your efforts!
