### ISSUE TITLE
Adding Chechen (Shishani) translation 

### ISSUE THREAD

**Issue by Marsho** [quran/quran_android#295]
Assalamu aleykum brothers! May Allah reward you for your excellent work.

I am interested in adding to your program a translation to the holy Quran in Chechnian (Sheeshani) language. I have the entire text fully translated, but have yet to figure out means of publicizing it. If possible, I would greatly appreciate help in finding out whom to contact, and what to mention in order to accomplish this task. 

Translation is all sunni and in .rtf format. Other version of translation is in .doc format.

Thank you in advance!

**Comment by Marsho** [comment]
Assalamu aleykum,
well, it's been a long time, a lot of stuff happened, but i'm still here with an idea to add a translation :) 
are you guys still interested in adding a Chechen translation, and do you still need the excel format you mentioned for that? And if so, can you tell me, if it will be easy to update the translation, for the author of translation is working on new edition of it, and if there is no option to update, he asks us to wait for few months more, in order to have newest edition.

**Comment by ahmedre** [comment]
wa3laikum alsalam @Marsho,
most certainly would love to have it. if you can send me a sqlite database, happy to have it, as long as it's a sunni translation (which insha'Allah it should be?) otherwise, csv format (sura, ayah, translation, one on each line for each ayah) would work too.
jazakAllah khairan.
walsalam 3alaikum.

**Comment by Marsho** [comment]
yes, it's a Sunni translation, for 100% of Chechens are sunni muslims. Ok i got it, i'll send it to you as soon possible (do you want me to upload it here or should i use email for that?).

so what about an updating the translation, will it be possible to update it when the new edition will be ready in few months?

wa iyyak,
wa alaykum assalam.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
sure, you can add it here or email it, whichever is more comfortable for you.
this is all controlled server side, so we don't need a new release to do it.
walsalam 3alaikum.

**Comment by movsar** [comment]
@ahmedre assalam alaikum, I'm working with @Marsho on this idea to add the translation and currently I hold it in .doc file format, I can convert it to fit to the necessary excel form but I have one question.
In those translations, there are many footnotes to the translated text, where the meanings of certain words and phrases are explained from author's perspective, so this creates the question: does your platform support adding notes to the translated text's words? Or must we left out them to make it work?
![untitled](https://cloud.githubusercontent.com/assets/18250365/22395443/50471f72-e54f-11e6-94be-b39c135f1136.png)

**Comment by ahmedre** [comment]
wa3laikum alsalam,
awesome, may Allah reward both of you!

that's up to you - we don't support footnotes now, so i think you have 3 options:
1. only add the translation.
2. add the translation and footnotes within it for each ayah.
3. we can discuss and figure out a way to implement footnotes within the app.

walsalam 3alaikum.

**Comment by movsar** [comment]
[FOOTNOTES]
So we decided that we will prepare the text without the footnotes, but we would like to add some description if there is any possibility in the application that there is a full version out there with the footnotes so they could be warned that it is not the complete work as it were printed in a book form.

Also we would like to propose this feature to be implemented in the app in the future if your team will have possibility and want to do it. I think there are still other translations also which are already included in the application with compliance of its standards even though in the original texts they may have some kind of additional notes. 

But we understand that you may need some work to do about it and time, so we are not "recommending" it or having a strong opinion on it because we don't feel that we are in the right position to do that. We are happy to have your application as it is now, and this chance to put our texts into it is very valuable to us. What we are saying is that if this feature as described above will ever be presented, we will be even more happy and grateful!)))

[CONVERTATION]
As I wrote in the previous message, we hold the texts in .doc file format. We are planning to convert them to HTML first, then clean it from unnecessary tags and styles, and then split the ayats and put them into excel file. We want to convert it initially to HTML because we want to save (with links) the footnotes for other project (we've got an app with chechen-only translation in it, so we'll be only updating its text. The reason why am I telling you this, is because I wanted to share the method that we will be using for the converting. This method may take a week or two before it's all done so if by chance you will have any better suggestions how to do that without HTML please share with us, we will be most thankful!

**Comment by ahmedre** [comment]
jazakAllah khairan, sounds good!

**Comment by Marsho** [comment]
@quranacademy wa aleykum assalam! vaystudio at gmail

**Comment by movsar** [comment]
@ahmedre at last I have managed to transform the files to the csv format, please let us know what else would we need!

https://drive.google.com/drive/folders/0B1N9Td4ah2QWWjBIanUxbFJQSTg?usp=sharing

**Comment by Marsho** [comment]
@ahmedre @afarra @hmaher @wnafee @mahmoudhossam assalamu aleykum brothers, wishing you blessed Ramadhan! and kindly asking if you could answer above, if the work which Movsar did is enough for our idea? 

jazakumullahu khayr!

**Comment by Marsho** [comment]
@ahmedre @afarra @hmaher @wnafee @mahmoudhossam assalamu aleykum dear brothers, can you please answer above, if the work which Movsar did is enough for our idea? we're still waiting for the answer, since we did what you asked for.

jazakumullahu khayr!

**Comment by ozbek** [comment]
The real issue here, I think, is the project owners have no way of verifying the translations. Hence, is the wait @Marsho.

**Comment by Marsho** [comment]
assalamu aleykum brothers,

@ozbek but i was never informed about that. also, brothers just stopped answering and reacting in any way. i have no idea for what am i waiting. the thing is, that i asked a brother of mine to help and he did huge amount of work by transforming the files to the format which our admins asked all by himself, manually. and since then, there is just no any reaction, any information, any clarification on what the plans or problems are. 

@ahmedre @afarra @hmaher @wnafee @mahmoudhossam

**Comment by mahmoudhossam** [comment]
@Marsho I have not contributed code to this project since 2011, please refrain from mentioning me.

Thank you.

**Comment by naveed-ahmad** [comment]
@Marsho @movsar @ozbek Assalamu aleykum brothers, wow this issue been opened from five years! 

Good news is we've implemented foot notes functionality, please attach latest translation with footnotes in doc format and i'll add it into quran.com(web app) inshAllah.

**Comment by movsar** [comment]
Dear @naveed-ahmad ,

Thank you for lettings us know about the recent update and ability to integrate the Chechen translation.
Please review [the post I left before ] https://github.com/quran/quran_android/issues/295#issuecomment-294916096 it contains a link to the translation in *.doc format. 

If you need any information or some sort of official approval of its consistency and legitimacy, just let us know, what exactly and in which form you need. In such case we will meet the author of this translation and / or ask official representatives of Russian Islamic University in Grozny for help.
[QuranChechen-20180329T163503Z-001.zip](https://github.com/quran/quran_android/files/1861069/QuranChechen-20180329T163503Z-001.zip)

**Comment by naveed-ahmad** [comment]
@movsar do you want to add footnotes? If yes then please send updated docs file, see the attached docs file to see the format.

https://docs.google.com/document/d/1kt2NQnve_b1OZp8nWummLkG3l62cMXeuDaiu8ZtstPk/edit?usp=sharing

But if simple translation is fine, then csv would works.

**Comment by movsar** [comment]
@naveed-ahmad
oh, sorry, I thought those files included footnotes.
here, those are the originals https://drive.google.com/open?id=0B1N9Td4ah2QWbzl1ekxCT3NjQVU

**Comment by naveed-ahmad** [comment]
@movsar I don't want to increase work on your side, this issue should have been closed years ago :( 
But parsing one file be much easier, do you've one docs with whole Quran?

If not, please export all docs as html and send the zip or you can upload each file to google docs and export them as html. Parsing html files is much easier than docs. You can leave the Arabic, no problem. Here, I've uploaded the surah Fatihah for your reference.   

https://docs.google.com/document/d/1BSwlm9O5YVpPYfT134Y5aOLQEbQXrXZ2QA5Y4IhhgEo/edit?usp=sharing

naveedahmada036@gmail.com, please send zip on my email and ill parse them inshAllah.

**Comment by naveed-ahmad** [comment]
@movsar ^^

**Comment by movsar** [comment]
@naveed-ahmad sorry for my delay. Currently I am superbusy at my work and can't make time for it now. Hopefully I will combine all the files into one in Friday, but only as a *.docx format because converting it to clean html from *.docx is a heavy work, at least for me. So, if you will be able to convert it by yourself, I can combine the files in Friday and upload, if not, we'll have to look for someone to do the convertation and that might not be soon (((

**Comment by naveed-ahmad** [comment]
@movsar I think combining 114 files into one docs is time consuming, then you can just export this in html with single click :) 

No problem, send the docs and i'll do the rest inshAllah.

**Comment by Marsho** [comment]
Assalamu aleykum, brothers! Ramadan Mubarak!
So i just merged 114 doc files into one, using the standard MS Word (insert from a file) function. Can you please check it and say if it will work?

@naveed-ahmad 

https://drive.google.com/file/d/1wMd40KOJa7R_A4rnZtWUl5btC42AnyJb/view?usp=sharing

Jazakumullahu khayr in advance.

**Comment by Marsho** [comment]
@naveed-ahmad

Issue up

**Comment by Marsho** [comment]
@naveed-ahmad 

Still have hope for reaction

**Comment by naveed-ahmad** [comment]
@Marsho can you send me an email naveedahmada036@gmail.com there are some issues that we need to discuss before publishing this translation. Sorry I had parsed this translation months ago but forget to reply here.

**Comment by Marsho** [comment]
Allahu Akbar.

**Comment by Marsho** [comment]
@naveed-ahmad assalamu aleykum bro. so, i can't find it live still. only on staging.quran.com

**Comment by ahmedre** [comment]
salam 3alaikum akhi,
for the web, in sha' Allah really soon - it's on beta.quran.com now which we've tried to push to prod a few times already but had to back out due to technical problems. in sha' Allah hoping very very soon.

in the meanwhile, will try to import this for the mobile apps.
jazakumAllah khairan for the effort and really sorry this took so long :(
walsalam 3alaikum.

**Comment by Shishaniyah** [comment]
> Assalamu aleykum brothers! May Allah reward you for your excellent work.
> 
> I am interested in adding to your program a translation to the holy Quran in Chechnian (Sheeshani) language. I have the entire text fully translated, but have yet to figure out means of publicizing it. If possible, I would greatly appreciate help in finding out whom to contact, and what to mention in order to accomplish this task. 
> 
> Translation is all sunni and in .rtf format. Other version of translation is in .doc format.
> 
> Thank you in advance!
> 


Assalāmu ‘alaykum warahmatullāhi wabarakātuhu 

Where can I find/download the translation of the Qur'an in Chechen?

**Comment by Marsho** [comment]
Wa ‘alaykum assalām warahmatullāhi wabarakātuhu

It's available on quran.com (choose it from "translations"). Also you can find chechen text itself here https://play.google.com/store/apps/details?id=com.nohchiyn.quran

**Comment by naveed-ahmad** [comment]
You can get the whole translation in JSON format using quran.com api 

https://api.quran.com/api/v4/quran/translations/106

**Comment by Shishaniyah** [comment]
> You can get the whole translation in JSON format using quran.com api 
> 
> 
> 
> https://api.quran.com/api/v4/quran/translations/106?fields=verse_key

Hard to read and too confusing.
Eitherway, I got the link I wanted, Del rez hül:)
