### ISSUE TITLE
poor search quality

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#427]
from an email:
- When search "idhrib" (اضرب) it doesn't show results about "wa
  idhrib" (واضرب), and when search "dharaba" (ضرب), it doesn't show
  results about "madhrib" (مضرب)
- When search "wa" (و) it doesn't show more than 150 results although
  there is "22,226" result for this phrase.

**Comment by khalid-hussain** [comment]
Another one. The occurrence in Surah Qaf is not shown unless 'و' is added. Screenshots follow:
![](http://s25.postimg.org/selw48jv3/Screenshot_2015_01_28_21_32_58.png)
![](http://s25.postimg.org/kadrzhxfz/Screenshot_2015_01_28_21_33_04.png)

**Comment by ahmedre** [comment]
no response if search for راعون

**Comment by ahmedre** [comment]
> if I search "جاهدوا" there are many ayah that doesn't show up just because they're not exactly "جاهدوا" but "وجاهدوا".

**Comment by ahmedre** [comment]
> In the Quran app for android, the search engine can't find the word 'قتلهم' in chapter Ale Imran, verse 181. 

> Also, it can not find verses when you start searching with the و or even when it is in the middle of an aya.

**Comment by Ahmed9914** [comment]
It's obvious that this problem occurs because there is no space between واو العطف and the next word (search for "*و" to identify the problem), so I suggest a hack for solving this by adding واو in the begining of each search which doesn't start already with واو , we will face a problem with words like: 
وصية- ولدا- واديا -وسع- واسع- وابل -وازرة -وزر- ورق........

If we managed to filter these words to show them only if the search starts with واو, then we solved this issue.

Seems not wow solution but I think it will work until we can find a better offline solution.

و جزاكم الله خيرا
