### ISSUE TITLE
Color-coded tajweed rule support

### ISSUE THREAD

**Issue by theimpostor** [quran/quran_android#439]
Adding an option to change the color of the font for certain letters based on tajweed rules would be a useful option, especially for beginners. This could help reduce errors in recitation, for example.

I understand this might be a lot of work. Where would one begin to try and implement this?

**Comment by Muhammed1111** [comment]
السلام عليكم ورحمة الله وبركاته،

I am willing to finance this project.
It can benefit alot of Huffaaz.
We need the different Qiraat color coded according to the latest version available. 
I think that the best option is a hiqh quality bookprinter. 
Once we have acquired one we can digitize many more Islamic books. 

 جزاكم الله خيرا

ج

**Comment by mouss-delta** [comment]
Assalam ahlikoum,

Just for information, Dar Al Maarifa Quran's page images are available here : http://www.easyquran.com/ar/prepage-ar.htm

For Hafs with tajweed coloration : http://www.easyquran.com/quran-jpg/index.php
For Warch with tajweed coloration : http://www.easyquran.com/quran-jpg-w/index.php

**Comment by murtraja** [comment]
@ahmedre I would like to work on this. Can you suggest where should I start?

**Comment by Muhammed1111** [comment]
The thing is that the pages of the Quran on that website are not HD you can see its bad quality.
I mean somebody did it on IOS with high quality images so I don't understand why the same couldn't be done for android devices.
I am planning to switch to Apple if it doesn't happen on the android because it is a great help especially for women. Because they aren't always pure anyways if it is to be done I am willing to be part of the sponsors.

جزاكم الله خيرا

**Comment by murtraja** [comment]
![image_info](https://user-images.githubusercontent.com/7806954/54087649-dd564380-437a-11e9-89aa-bf9cc1ff41bf.JPG)
@Muhammed1111, isn't ~1080p enough for HD?

**Comment by Muhammed1111** [comment]
It doesn't look HD to me tbh

**Comment by Muhammed1111** [comment]
Idk how the pages on the Quran app were acquired however ما شاء الله لا حول ولا قوة الا بالله they are very clear and sharp and bright.

**Comment by ahmedre** [comment]
can we get someone to get a good quality copy of the tajweed mushaf (with heavy pages that aren't transparent) and do a high quality scan of them instead?

**Comment by ahmedre** [comment]
fwiw, after some time, we started scaling down the images served on Quran apps because it didn't seem to make a massive difference (versus it made a massive difference in both space taken to download the images and in the time to switch between pages). so right now, the highest quality images are just over 1080p. these might be okay, but would need a bunch of work to make them work properly (i.e. removing the borders, make them transparent, etc).

**Comment by Muhammed1111** [comment]
We probably have 3 options.
1. As akh Ahmed suggested somebody needs to obtain a good quality of the tajweed mushaf with heavy pages and then perform a high quality scan
2. We ask our brothers from the IOS app of a copy of the images of the tajweed Quran that daar al maarif provided them.  
3. We directly ask daar al maarif directly for high quality image scan performed on a good quality mushaf with heavy pages

NOTE: This app features the newest print from Daral Maarifah and unlike other apps, it is legally licensed. The print is of top most quality obtained directly from Daral Marifah. By purchasing this app, you can rest assured that you have bought an authentic Daral Maarifah product.


Introduction:

SHL info systems, in collaboration with Daral Maarifah, presents “ The most advanced Quran application ever made for a smart phone”.


This is a digital version of the popular color coded Mus'haf At-Tajweed published by Daral Maarifah. The new version has been written ground up aiming to provide excellent user experience and appealing design with actual book like interface. A number of new features has been added on top of what the old version of the app provided.

https://itunes.apple.com/us/app//id368876346?mt=8

**Comment by ahmedre** [comment]
sounds good - let's go with options 2 and 3 - we can email the iOS brothers and ask for a contact with Daral Maarifah and ask what we can do to get and use the images. since the app is paid, they may be asking them for a licensing fee of sorts, so we can see if we can work something out with them.

i found SHL info systems' email on their page, so i'll email and ask them and will update when i hear back in sha' Allah.

jazakAllah khairan

**Comment by Muhammed1111** [comment]
جزاكم الله خيرا

**Comment by mouss-delta** [comment]
If needed I have dar al maarifa images for which we have removed border, for hafs and warsh. If needed I can give it to you (by ftp or any other mean). Here is the final look of the image when border are removed.
![page005](https://user-images.githubusercontent.com/26151311/54092497-1c8d9000-438d-11e9-887b-e69dcc7190e7.jpg)

**Comment by murtraja** [comment]
Also, if needed, I might be able to generate QA style (glyph_id, page_number, line_number, sura_number, ayah_number, position, min_x, max_x, min_y, max_y) database for these images. 
(The glyphs will be segments of the ayat that span a line and not the word)

**Comment by mouhanad1053** [comment]
> السلام عليكم ورحمة الله وبركاته،
> 
> I am willing to finance this project.
> It can benefit alot of Huffaaz.
> We need the different Qiraat color coded according to the latest version available.
> I think that the best option is a hiqh quality bookprinter.
> Once we have acquired one we can digitize many more Islamic books.
> 
> جزاكم الله خيرا
> 
> ج

بسم الله الرحمن الرحيم In the name of Allah, Most Gracious, Most Merciful

ASA,

After seeing this issue and with the help of Allah, I have created a platform which can support multiple versions of Quran. I currently have mushaf al-Madina and mushaf al-mujawwad and I recently added the pages from Qaloon-An-Nafi3 from islamweb.net. The platform allows for adding any books on-demand so we can have all the 10 Qiraat in 1 app, IA. 

The consumer of this platform is currently an Android app. I am about 85% ready to go live. I have been working on my own but I am in need for some expert help. If there is still interest in contributing to and/or financing this project please contact me for details. I have gained a lot by learning from QuranAndroid and others like quran.com. 

Based on https://github.com/quran/tajweed I have also set up a quick web page with all the ayas generated in png with colored tajweed codes (still need to add some tajweed  rules and regenerate). it can be viewed at  https://indie-publishing.space/main/publishers/Assala/Quran/show-sura.php. If interested, you can find my contact on that page as well.

جزاكم الله خيرا

**Comment by HiIAmMoot** [comment]
> Also, if needed, I might be able to generate QA style (glyph_id, page_number, line_number, sura_number, ayah_number, position, min_x, max_x, min_y, max_y) database for these images. (The glyphs will be segments of the ayat that span a line and not the word)

I have enhanced and added transparency to the tajweed pages. They should be high quality enough for the usage of the app. I can also provide cropped if need be. FIlesize is big though (9GB) so it should be sized down to a common size like 1920 or 1260 (whatever the app uses). I am also working on expanding the code to support a tajweed page type but will need help with the database etc. Could you help me with that?

The enhanced images you can find [here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/images-enhanced/images)

**Comment by murtraja** [comment]
Recently, I got the opportunity to segment the Tajweed pages word by word. Since I have the code ready (might have to modify a bit here and there) I should be able to help you with minimal efforts. 

https://user-images.githubusercontent.com/7806954/161809018-f4748571-94ab-4d8d-804e-6a78ddd85f52.mp4

**Comment by mouhanad1053** [comment]
I have the Quran almujawwad at
https://www.indie-publishing.space/self_publish_app/#/
Please check that put and let's discuss where we need to improve

**Comment by HiIAmMoot** [comment]
> Recently, I got the opportunity to segment the Tajweed pages word by word. Since I have the code ready (might have to modify a bit here and there) I should be able to help you with minimal efforts.
> 
>  output_file.mp4

Amazing! I should be able to get this into the app in no-time. What resolution should I scale the images? I've also fixed the problem of the first 2 pages by cropping them to match the resolution of the rest, so there might be no need to take measures for that anymore.

**Comment by murtraja** [comment]
I don't have a clear answer to that as depending on the device, we download different resolution images. The resolution for Tajweed pages that I have worked with is 1053 x 776 (ratio: 1.357) and the pages which you have shared are 4208 x 3104 (ratio: 1.356)

The resolution that I have worked with mostly in Quran Android is 1656 x 1024 (ratio:  1.617). These are cropped images, so the ratio is greater than Tajweed.

I leave this upto you to decide. Having said that, since we are finding the word segmentation and preparing a database, it really doesn't matter right now as even if we choose say H x W and then in the future change it to H' x W', as long as the ratio remains the same, the entire database can be scaled up or down and the coordinates will be mapped correctly.

For the sake of processing, I would like these images to be somewhere near 1053 x 776 as I don't have a lot of computing power to tackle high res images. Once we have the db ready, you can decide on a good resolution and scale the db accordingly

Try to play with the images with different resolutions and styles here:
https://quran-android-images-helper.herokuapp.com/?images=1024
https://quran-android-images-helper.herokuapp.com/


try changing images param to 1920, 1260, you can also add safah=3 param to open a specific page

source: https://github.com/murtraja/quran-android-images-helper

**Comment by HiIAmMoot** [comment]
I will aim to keep the ratio consistent, so i will resize the pages to be 2106x1552 (2x scale) or 3159x2328 (3x scale). That means that for processing you can keep the same images you are using now and add a multiplier as you mentioned.

I will do scaling at the final step as I prefer working hi-res when making edits. Am working on isolating the black texts so i can invert it for dark theme.

Also, if you need processing power. I can always help out, I have 2 fairly specced laptops that can run things.l, or you can use https://colab.research.google.com/ for cloud processing(is what I used for cleaning and upscaling the images). It really helps!

**Comment by ahmedre** [comment]
@HiIAmMoot masha'Allah amazing work! what is the source of these images, and are we confident that the processing did not inadvertently remove / modify the text (i.e. sometimes when running processing, it causes some of the tashkeel to hide, etc). this will make life a lot easier in sha' Allah for adding things. previously, we were using [ayah-detection](https://github.com/quran/ayah-detection) for detecting ayah marker locations and generating the database, but what Murtaja shared seems more promising.

@murtraja sub7anAllah amazing - I wanted to write a tool to do exactly what you have there, because I wrote some code to use Google's OCR and some custom code to try to find the word locations in the newer madani mushafs, but realized that it would need manual editing to finish the job. is there a way you can share this tool for use and/or open source it? also, am curious how you got the initial word bounds in the first place.

jazakumAllah khairan both for this amazing work!

**Comment by mouhanad1053** [comment]
> @HiIAmMoot masha'Allah amazing work! what is the source of these images, and are we confident that the processing did not inadvertently remove / modify the text (i.e. sometimes when running processing, it causes some of the tashkeel to hide, etc). this will make life a lot easier in sha' Allah for adding things. previously, we were using [ayah-detection](https://github.com/quran/ayah-detection) for detecting ayah marker locations and generating the database, but what Murtaja shared seems more promising.
> 
> @murtraja sub7anAllah amazing - I wanted to write a tool to do exactly what you have there, because I wrote some code to use Google's OCR and some custom code to try to find the word locations in the newer madani mushafs, but realized that it would need manual editing to finish the job. is there a way you can share this tool for use and/or open source it? also, am curious how you got the initial word bounds in the first place.
> 
> jazakumAllah khairan both for this amazing work!

I have generated the Aya location databases for both mushafs Almadina and Alumujawwad. However I didn't crop the page and kept the margins. I should be able to use the cropped pages and re-generate the db, if that helps here.
Ramadan Kareem everyone.

**Comment by HiIAmMoot** [comment]
> 

Thank you. I currently have no means of checking if any information was lost. However, the algorithms used are ARCNN which just removes jpg artifacts, and ESRGAN which upscales images. It could've happened that ESRGAN smoothed things out, however I chose a model that isn't as agressive so details should be preserved and it only sharpened. @murtaja 's tool can seemingly match the images with actual arabic text. So I could maybe do validation run and see if there's any inconsistencies that way.

**Comment by murtraja** [comment]
I will definitely open source the tool after some refactoring, but let me summarize how it works.
There are two parts to it. The first one is a stupid and simple algorithm to segment the words and generate a confidence score.
The second part is the "interactive word corrector" which I have shared.

The algorithm is so simple, you will not believe me. I start from the right, start of the line. Let's call this x position as my cursor. From the cursor, I jump to `cursor - word_width` where word_width is just a guess of how long the next word is going to be. This guess is calculated by using the Quran Android Images repo. I "draw" the word by using the fonts present in that repo and simply measure the width.

Now I fine-tune the word boundary by looking at the empty pixels surrounding the jump (call this search vicinity). If I find a "wall" of empty pixels, I am good and I move on to the next word. The problem occurs in cases where the next word starts with kaaf as then my current word and the word starting with kaaf overlap. In this case, where I am not able to find the "wall" of empty pixels, I resort to pixel-by-pixel template matching. Since I had previously "drawn" the word using the fonts, I just compare the "drawn" word with the current word and expand or contract the jump boundary depending on the score of the template matching algorithm.
![step1](https://user-images.githubusercontent.com/7806954/162048386-f3dcf2af-dde5-4e4e-ac66-59bce6349c24.png)

![step2](https://user-images.githubusercontent.com/7806954/162049502-ef8c4685-b89d-42d1-8132-096e4a86577c.png)

Using this approach I was able to make a good 75 to 80% progress. I already knew what words are present on the individual lines thanks to the database schema diagram present in the repo. Then for the remaining 20% words, I created the interactive word corrector.

@HiIAmMoot is it possible if you can downscale the images and provide a link? I will then start processing the images. Also, in the meantime, let me share the Tajweed db with you after I scale it to the resolution which you have given. If the pages/fonts are identical, it should work out of the box without having to run the algorithm.

**Comment by ahmedre** [comment]
@HiIAmMoot jazakumAllah khairan, this looks good! we can in sha' Allah see about getting manual review for the pages to be sure before releasing.

@murtraja masha'Allah, this is great! maybe we can combine the approaches (Google OCR first, falling back to your technique of estimating) and that should give us better estimates in sha' Allah. please keep me posted about this!

**Comment by HiIAmMoot** [comment]
@ahmedre yes it is best to do a manual review. If you see patterns of inconsistencies then I might have to edit the postprocessing. For example, I just noticed that the dammas on the letter ه when they're greyed out, it becomes hard to read due to its small size. I have made the gray letters a bit more obvious so in sha Allah that is fixed. If there's still issues with this, there's ways to fix it if I can detect on what page and where this happens, @murtraja could probably help with that if the time comes.

There's also the issue of filesize. The 1552x2106 pages are 3.25GB in total. I am looking into optimization, what is acceptable in terms of filesize?

@murtraja you can find 2106 resolution pages [here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/images-enhanced-2106/images). The image ratio is corrected so whatever work you've done so far you can keep if you upscale it 2x.

**Comment by ahmedre** [comment]
I'd vote without the side area (because the mobile screen is already small, and the words described on the side can be read by downloading the "Arabic Word Meanings" tafseer present in the app). For the size, I'd go smaller - a width of 1280 or 1260, and then apply very heavy compression - I think the largest image set we have in the app today is probably less than 150mb, so our target would be there.

With respect to dark theme, I'd vote just for transparent images - with that we can apply a filter (which is what we do today) to the text to render dark theme.

Also, for saving size, I'd cut the border and the description of the colors - we can find a way to add a single image somewhere describing what each color is, but paying this number of pixels per page will make a large difference. Because these pages are likely uniform (or at least the odd ones and even ones are probably so), we can write a command line script to pretty easily just keep the piece in the middle (using `mogrify` (part of ImageMagick) with a `-crop` parameter). We did this before for another page type before.

jazakumAllah khairan!

**Comment by HiIAmMoot** [comment]
I have means to get rid of the borders and provide just the text. I will provide new images soon then, in sha Allah.

**Comment by HiIAmMoot** [comment]
Ok I got it cropped. Still working on enhancements though.
Got it [here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/images-original/images) 
![image](https://user-images.githubusercontent.com/13383284/162595292-31eef97a-e52d-4543-aa5c-864bd5c627b8.png)

**Comment by benomaire** [comment]
@HiIAmMoot
1. Your [first upscale](https://github.com/quran/quran_android/issues/439#issuecomment-1089021891) used [this source](https://www.easyquran.com/quran-jpg/index.php). I want to ask what is the source used for [the recent cropping](https://github.com/quran/quran_android/issues/439#issuecomment-1094142708), and did you upscale then downscale?
2. 857*1262 is small IMHO.
3. Do you think the process of inverting just the black text can be implemented in the app? because using non-transparent two sets of images will force two backgrounds: white or black. Not to mention doubling the size.

**Comment by ahmedre** [comment]
2. yes, want a width of 12xx and a height accordingly.
3. we have some scripts in [ayah-detection](https://github.com/quran/ayah-detection) to transparent the images so we can programmatically invert the text like we do for the other image types.

**Comment by HiIAmMoot** [comment]
> @HiIAmMoot
> 
> 1. Your [first upscale](https://github.com/quran/quran_android/issues/439#issuecomment-1089021891) used [this source](https://www.easyquran.com/quran-jpg/index.php). I want to ask what is the source used for [the recent cropping](https://github.com/quran/quran_android/issues/439#issuecomment-1094142708), and did you upscale then downscale?
> 2. 857*1262 is small IMHO.
> 3. Do you think the process of inverting just the black text can be implemented in the app? because using non-transparent two sets of images will force two backgrounds: white or black. Not to mention doubling the size.

The latest crops are NOT upscaled yet.

I got the pages from easyquran-eg.com. [Here](https://www.easyquran-eg.com/qrhafs/assets/frontend/dist/img/003.jpg) is a direct link to the page.

2. My target resolution is to make the smallest dimension 1260. So the final resolution will be somewhere around 1260x1855.

3. We can use transparent image and a separate mask for the black text. @ahmedre the issue with using detection is we need to prevent the colored text from inverting. The dark theme example I posted was achieved with a mask like this.
![image](https://user-images.githubusercontent.com/13383284/162616016-d0858cc7-05e7-4326-9f42-933a0645d673.png)
These will roughly be a third of the original filesize. So adding support through this mask will have a 33% increase in size instead of doubled(by my estimate).

**Comment by ahmedre** [comment]
if the images are transparent, you don't need to do anything to support it - we can mask it in the code (which is what we do today) - you can see the code [here](https://github.com/quran/quran_android/blob/ba41a90320623bd9f1831a2c3a51964ab276a8bb/app/src/main/java/com/quran/labs/androidquran/view/HighlightingImageView.java#L360).

**Comment by HiIAmMoot** [comment]
> if the images are transparent, you don't need to do anything to support it - we can mask it in the code (which is what we do today) - you can see the code [here](https://github.com/quran/quran_android/blob/ba41a90320623bd9f1831a2c3a51964ab276a8bb/app/src/main/java/com/quran/labs/androidquran/view/HighlightingImageView.java#L360).

I see, then we will do that.

**Comment by benomaire** [comment]
I asked for the new dark approach because I have seen [someone](https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.warsh&hl=ar&showAllReviews=true) complaining that colors in dark mode are not easy on the eyes, but that could be because of the solid black background. 



> 1 سبتمبر 2021
4
تطبيقٌ معشر المغاربة كنا في حاجة إليه.. لكن ليتكم تحذفون الألوان من الحروف، فإنها في الوضعية الليلية تكون مؤذية للعين


The current approach is definitely easier but it flips the colors (e.g. the green becomes red and vice versa). I'm sure you are aware of this but mentioning it to make sure everybody is on the same page. I mean there will be a compromise either way.

**Comment by HiIAmMoot** [comment]
Yeah if this can be remedied with the new approach then all is well in sha Allah.

Another question, we are now communicating purely through git issues, is there an alternate means of communications you adopt? Like a discord or something?

**Comment by ahmedre** [comment]
we are on the quran.com Discord - you can join here - https://quran-community.herokuapp.com

**Comment by HiIAmMoot** [comment]
@ahmedre new set of enhanced images are done. Got a resolution of 1280x1890. You can find em [here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/images-enhanced/images). I've also tried a [256-color version of the images](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/images-enhanced/images/indexed) to reduce filesize, those are around your benchmark of 150 MB, but some quality is sacrafised. You'll have to check yourself which you prefer. I believe I can find some middle ground but if 150MB is your goal then those are the closest you'll get I think.

@murtraja is this sufficient for you to do your thing? The ratio is different from the previous set but it shouldn't change further.

In sha Allah we can now proceed to manual clean-up and checking the pages for errors.

![image](https://user-images.githubusercontent.com/13383284/163395112-a5449785-eb1b-499a-9f76-26bfdcf62893.png)

**Comment by ahmedre** [comment]
masha'Allah, awesome! I did a quick look and the originals can still be reduced some (~11%ish via ImageOptim), and ~6% for the 256 images - the two look very similar to me, so I think we'd need to go with the 256 ones since the size will be prohibitive otherwise.

if Murtaja's work doesn't translate to this, we can use [ayah-detection](https://github.com/quran/ayah-detection) to detect the ayah markers to unblock this.

**Comment by murtraja** [comment]
@HiIAmMoot I think the following operations will fix the geometry
1. Perform origin shift (translation) to account for the trimmed borders in the 776 x 1053 images and convert them to 616 x 905 (In other words, subtract left border size from x coordinates and subtract top border size from y coordinates)
2. Scale x coordinates by 1280/616 = 2.0779 and y coordinates by 1890/905 = 2.0884

Also I realized that the db that I created has only word segmentation entries - it doesn't have information regarding "hizb", "ayat end marker" or "sajda" glyphs. What this means is that the user will not able able to interact with these glyphs in order to perform ayat specific operations. So I will have to add support for this.

Moreover, in this [comment](https://github.com/quran/quran_android/issues/439#issuecomment-1089433227) you talk about using a CNN to remove jpeg artifacts. I realized that there are clean .PNG files available here: https://app.quranflash.com/book/Tajweed/epub/EPUB/imgs/003.png (You might have to automate downloading all 604 images, though). These files are 776 x 1053. If you have any concern that the CNN doesn't undo the effects of DCT / JPEG compression, maybe try these as your starting images?

**Comment by HiIAmMoot** [comment]
@murtraja the newest source I've used doesn't have much jpeg artifacts and js a higher resolution. So I think I stick with that ine because it really helps with the smaller dhammas. However, it was good to run it through CNN regardless because that made the upscale cleaner. I can show a comparison between running ESRGAN on the raw and the ARCNN'd image if you're curious.

To clarify what I've done so you know how I've come to the final resolution:
- Downloaded pages from [Easy Quran](https://www.easyquran-eg.com/qrhafs/assets/frontend/dist/img/003.jpg) uncropped (resolution 901x1476)
- Cropped to just text, cleaned the borders (resolution 857x1262) 
- Added 1px margin to avoid upscale artifacts (resolution 859x1264)
- Ran images to ARCNN to clean them up and prepare them for ESRGAN
- Ran images through ESRGAN (resolution 3424x5056)
- Removed white bg and scaled down while maintaining the ratio (resolution 1280x1890)
- Saved as indexed 256 colors to reduce filesize

**Comment by mouhanad1053** [comment]
> masha'Allah, awesome! I did a quick look and the originals can still be reduced some (~11%ish via ImageOptim), and ~6% for the 256 images - the two look very similar to me, so I think we'd need to go with the 256 ones since the size will be prohibitive otherwise.
> 
> if Murtaja's work doesn't translate to this, we can use [ayah-detection](https://github.com/quran/ayah-detection) to detect the ayah markers to unblock this.

I have used ayah-detection to generate a .json index of the ayahs' marker coordinates, found [here](https://indie-publishing.space/main/EnhResAyaCoord.json). The .json include the number of Ayahs which were detected. I did a visual check with the images as shown below. 
As an addition check, a script could be written to cross check the number of Ayahs for each page to verify that produced number of detected ayah markers match actual number of ayahs. 
I hope this helps.
![593](https://user-images.githubusercontent.com/85943695/163479538-47e14d9f-680d-44a1-a701-eac7cbdf2bd4.png)

**Comment by HiIAmMoot** [comment]
Ok ok, did something happen in the past week or something..?

Easyquran.com now provides high quality pages!

![image](https://user-images.githubusercontent.com/13383284/163596321-02998102-2550-4a13-ae1e-b24e76768bf8.png)

@ahmedre should I process these instead?

**Comment by ahmedre** [comment]
wow, masha'Allah! yes, if we can avoid our image processing steps, then in sha' Allah we won't have to do manual review.

@mouhanad1053 jazakumAllah khairan! if we're re-doing the images though might need another one in sha' Allah

**Comment by HiIAmMoot** [comment]
@murtraja @ahmedre  new images are up!

Find em [here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/images-enhanced/images/indexed) 

There is still an issue with the bg I fill fix  but the database can be updated with these images.

In sha Allah these dimensions (1680x1883) are final!

**Comment by ahmedre** [comment]
what's the overall size? afraid this will still be too big, especially since ~1280ish is a pretty common width, would aim to have that as the width if possible? what do you think?

**Comment by HiIAmMoot** [comment]
Subhan Allah, I meant 1280x1883, not 1680. My mistake!

**Comment by ahmedre** [comment]
perfect, jazakumAllah khairan!

**Comment by murtraja** [comment]
@HiIAmMoot , Finally managed to add the hizb, sajdah and ayat end markers in the db. Now I have to find the transformation parameters to match this resolution. Will share the db soon
![005](https://user-images.githubusercontent.com/7806954/163713536-3059b75b-c4f2-4a01-af3d-109c8789eda9.png)
![176](https://user-images.githubusercontent.com/7806954/163713543-0d4c8130-97ab-42b3-992b-f8f98cb5db6e.png)

**Comment by ahmedre** [comment]
masha'Allah, awesome!

**Comment by HiIAmMoot** [comment]
Ma sha Allah good work!

**Comment by nacer80** [comment]
Mash'Allah great job brothers.

**Comment by murtraja** [comment]
Hello,

Please find the 1280 db [here](https://drive.google.com/file/d/1-A0PXxWEw-FyO7dEQv2TiUBkt_scXGxa/view?usp=sharing). The values for pages 1 and 2 need to be manually worked out (WORK IN PROGRESS)

I did not get a clean formula for transformation so not very satisfied with it ( I was hoping the scaling factor to be exactly 2 :) )

I only tried the transformation on pages 3 and 4 so it should work for others as well.

Also, I am pasting the queries for my reference that I used to generate this db from the 776 x 1053 variant

```
create table glyphs as select word_id as glyph_id, page_number, line_number, sura_number, ayah_number, position, min_x, max_x, min_y-39 as min_y, max_y-39 as max_y from glyphs_1053
update glyphs set min_x = min_x - 28, max_x = max_x-28 where page_number%2=1
update glyphs set min_x = min_x - 125, max_x = max_x-125 where page_number%2=0
update glyphs set min_x=cast(round(min_x*2.0717277486910994) as int), max_x=cast(round(max_x*2.0717277486910994) as int), min_y=cast(round(min_y*2.0717277486910994) as int), max_y=cast(round(max_y*2.0717277486910994) as int)
 ```

To clarify, I am subtracting top border (39 pixels) for the very beginning while creating a new table. Next, for odd pages, the left margin is 28 pixels and 125 pixels for the even pages. Subtracting those as well. Now once the coordinates are translated, a simple scaling puts them in the right location.

The ratio is a magic number, I tried to get the ratio by dividing the new height with 1053, but it wasn't sufficient, so had to add a factor of 0.1 to make this work.

![3_transformed](https://user-images.githubusercontent.com/7806954/163728252-6e4dca4c-fc86-41e0-81c1-72dfe2927bb5.png)

Page 4:

![4_transformed](https://user-images.githubusercontent.com/7806954/163728254-fcfe7eaa-e0f1-4923-b2a8-993a394d6dc9.png)

**Comment by HiIAmMoot** [comment]
Ma sha Allah good work!

For the ratio, you took 1053/1883 + 0.1 = 0.659

The magic number you might be looking for is the ratio of the original page, which is 2067/2953 = 0.697. Not sure, but worth a try?

**Comment by JuanPotato** [comment]
Assalamu alaikum,

I was just thinking today about how I wanted to have the tajweed markings in this app and wanted to contribute. Nice work everyone!

I wanted to also be able to have the text in the translation screen also be color coded for tajweed. I use the translated screen to see both the arabic text larger and the translation at the same time. Is there already a database that holds the information for each letter's tajweed markings or is this something that I could help with?

**Comment by mouhanad1053** [comment]
@JuanPotato . Back in June 2021 and based on https://github.com/quran/tajweed I have set up a quick web page with all the ayas generated in .png with colored tajweed codes (still need to add some tajweed rules and regenerate). it can be viewed at https://indie-publishing.space/main/publishers/Assala/Quran/show-sura.php. If interested, I can share the code with you. You can easily add your code to generate the db. Please keep in mind that validation of the result is extremely necessary since it's easy to miss a glyph while processing.

**Comment by murtraja** [comment]
Please find the final db [here](https://drive.google.com/file/d/1I51eL14hewJaWWLxCDuCW94CcwWQscr7/view?usp=sharing).

Not sure why page 1 was distorted while displaying it using matplotlib though

![1_transformed](https://user-images.githubusercontent.com/7806954/165204012-989589c0-ef2c-4783-85a4-211a1883ea02.png)
![2_transformed](https://user-images.githubusercontent.com/7806954/165204027-9d4d6260-2169-4b44-ade0-246ddd7341ef.png)

**Comment by JuanPotato** [comment]
Where can I find the GreenTech code you're referring to? Is it just code that determines the tajweed for each character?

**Comment by ahmedre** [comment]
@murtraja masha'Allah, amazing! how accurate is the word by word data on this one? in sha' Allah will put an apk together with this shortly after Eid in sha' Allah.

**Comment by ahmedre** [comment]
@JuanPotato  - no, it's not open source - their algorithm doesn't use images, it's for colorizing text - similar to [our open source one](https://github.com/quran/tajweed).

**Comment by murtraja** [comment]
@ahmedre , I have manually verified all 604 pages (on the original resolution), so it should be 99.99% accurate. Give or take a few pixels here and there, the user experience will not be affected in any way.

Randomly verifiying the values on the scaled up pages is something that I haven't got a chance to do yet, but since it worked for pages 3 and 4, we should be good for other pages as well as it is only a matter of translating the coordinates and scaling.

**Comment by ahmedre** [comment]
@murtraja masha'Allah, amazing! would love to be able to use this for other image types to identify the word boundaries there also

**Comment by nacer80** [comment]
JazakumAllah khairan Akhi @murtraja 
Great job.

**Comment by ahmedre** [comment]
indeed, jazakumAllah khairan!

**Comment by ahmedre** [comment]
@murtraja can you join Discord - https://quran-community.herokuapp.com/ - please message me when you do in sha' Allah if you can.

**Comment by HiIAmMoot** [comment]
@murtraja there seems to be a bug in the ayah splitting. You can see it in page 538.

![Screenshot_20220512-160417](https://user-images.githubusercontent.com/13383284/168094006-960f2e5c-aadd-4e10-a8a6-6e19577cad50.jpg)

![Screenshot_20220512-160422](https://user-images.githubusercontent.com/13383284/168094045-46251de3-5ac7-40cf-bb33-fd54a281076b.jpg)

Also, a bug has been found with the cropping so I need to adjust the margin to 1280x1890. I will update you once I have done that.

**Comment by murtraja** [comment]
Please provide the link for updated pages for double confirmation

**Comment by HiIAmMoot** [comment]
[Here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/images-enhanced/images/indexed) you go.

**Comment by HiIAmMoot** [comment]
@murtraja any progress on updating the db with the new pages?

**Comment by murtraja** [comment]
@HiIAmMoot, sorry a bit occupied right now. Next week Insha Allah! I have two issues to look at
1. Some words show incorrect entries like in 538
2. Modify the db to make it work with new page dimensions

**Comment by HiIAmMoot** [comment]
Salam @murtraja @ahmedre I've managed to find some time to manually correct the DB in post using Python. This should be good to go, please test with new page dimensions.
[glyphs_final.zip](https://github.com/quran/quran_android/files/9439560/glyphs_final.zip)

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakumAllah khairan @HiIAmMoot.
I've uploaded the new images and database al7amdulillah. if anyone wants to test this, you can use [this apk](http://cafesalam.net/uploads//tajweed.apk).
walsalam 3alaikum

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
 
there are some Ayats highlighting issues.![Screenshot_20220911-133435.jpg](https://user-images.githubusercontent.com/60948528/189528039-a130a84a-4e41-4727-9e13-a1a83bd360ee.jpg)

**Comment by HiIAmMoot** [comment]
> السلام عليكم ورحمة الله وبركاته
> 
> there are some Ayats highlighting issues.![Screenshot_20220911-133435.jpg](https://user-images.githubusercontent.com/60948528/189528039-a130a84a-4e41-4727-9e13-a1a83bd360ee.jpg)

That's weird, I don't have these issues.
![Screenshot_20220911-144905](https://user-images.githubusercontent.com/13383284/189528577-602f84d3-986b-47dd-bb7f-5e63301fb49f.jpg)

**Comment by ahmedre** [comment]
just tested and I don't see this issue either - @nacer80 please remove the tajweed pages and ayahinfo database and try again - there's no built in upgrade since this is not released to the public yet.

**Comment by nacer80** [comment]
Yes, it's ok. 

JazakumAllaho khairan

**Comment by HiIAmMoot** [comment]
I've added some whitespace to the sides and updated the db accordingly. Please check it out @ahmedre

New images are [here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/tree/main/images/indexed)
The new db is [here](https://github.com/HiIAmMoot/quran-android-tajweed-page-provider/blob/main/glyphs.sql)

**Comment by ahmedre** [comment]
sorry it took so long - finally replaced these images. please remove the existing ones and try again in sha' Allah.

**Comment by HiIAmMoot** [comment]
Forgot to comment back, new images are good. Ready to ship in my opinion.

**Comment by ahmedre** [comment]
already shipped, still rolling out.

**Comment by manna06** [comment]
Assalamu’alaikum,

Is this open source? Can I use it for my app?
