### ISSUE TITLE
Android 5.1: Accept button in audio download prompt is not visible in landscape mode

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#517]
![tmp_30232-screenshot_2015-04-08-23-56-40-1298164581](https://cloud.githubusercontent.com/assets/452620/7048170/37ab2226-de4c-11e4-8e8b-618aae975c0e.png)

**Comment by ahmedre** [comment]
insha'Allah will fix this, it's really important. the worst example of this same bug (same cause) is that on tablet, the audio bar never shows up (because it gets hidden underneath the navigation bar, which, on tablet, is on the bottom of the screen).

this bug has something to do with where `fitsSystemWindows` is set to true in `quran_page_layout` (it's currently set on both the `ToolBar` (which works properly as can be seen in your screenshot) and the audio bar).

the documentation says:

> This function's traversal down the hierarchy is depth-first. The same content insets object is propagated down the hierarchy, so any changes made to it will be seen by all following views (including potentially ones above in the hierarchy since this is a depth-first traversal). The first view that returns true will abort the entire traversal.

i am guessing that we need to implement `fitSystemWindows` in `PagerActivity` to fix this properly.
