### ISSUE TITLE
Quran for ios?

### ISSUE THREAD

**Issue by arsenanai** [quran/quran_android#555]
Assalamaleikum, mr. ahmedre. Thank you a lot for developing such functional quran app. Do you plan to start developing ios version?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khairan - unfortunately not at this time, because there are many really good iOS quran apps - here are some:

some free Quran apps:
- ayah (https://itunes.apple.com/us/app/ayah-ayt/id706037876?mt=8)
- ayat (https://itunes.apple.com/us/app/ayat-holy-quran-ayat-alqran/id634325420?mt=8)
- kuwaiti financial house (https://itunes.apple.com/us/app/alqran-alkrym-ahda-mn-byt/id385990290?mt=8)
- mus'7af iphone islam (https://itunes.apple.com/us/app/iphoneislam-mushaf-mshf-ay/id328962407?mt=8)

some paid apps:
- quran reader (https://itunes.apple.com/us/app/quran-reader/id305902828?mt=8)
- iquran (https://itunes.apple.com/us/app/iquran/id285946052?mt=8)

walsalam 3alaikum.
