### ISSUE TITLE
Word (تترا) misspelled in Arabic in translation mode

### ISSUE THREAD

**Issue by abdarraafi** [quran/quran_android#566]
Aswrwb,

In Surat al-Mu'minoon (23:44) the Arabic from the translation section has the word (تترا) spelled with a yaa (ى), whereas the Arabic picture of the mus'haf spells it with an alif (ا).

Compare: https://www.dropbox.com/s/auip5k7xi4wgd88/Screenshot_2015-08-09-10-05-14.png?dl=0

To: https://www.dropbox.com/s/r4zxbywtqccsw5v/Screenshot_2015-08-09-10-05-04.png?dl=0

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
jazakAllah khairan, but this is not a bug - the text in the translation view is imlaei (written arabic), whereas the images are uthmani font (quranic arabic), and so this being different is normal. we don't use the uthmani arabic in the translation view due to fonts not being generally available to render uthmani text on android and various other devices.
walsalam 3alaikum.
