### ISSUE TITLE
not open source !!!!!!!!!!!!

### ISSUE THREAD

**Issue by ens4dz** [quran/quran_android#568]
First of all i am not good in english but pllllllllllllllllz
today i want to contribute with more ratio compressed images and found this great project closed source !!
Please we cannot tell someone to install app from closed source
this makes that project like others -ads,data collectors...-
We can't benefits from others ideas
We cant even know if developer account hacked and someone else edit the images.

**Comment by ahmedre** [comment]
you tell me what to do brother - when the code was open, we had people:

1. take the code and add advertisements above and below each page.
2. had people take the code and add spyware and malware on it and distribute it through other app stores.
3. had people take the apk and add tracking information, etc.

most apps today are not open source - and by open sourcing Quran, we allowed people an easy way to release fake versions or versions with things we don't want. this has the unfortunate effect of damaging the reputation of Quran Android, thus stopping us from getting any more users.

we still won't have ads, and, as usual, the only data we collect is all anonymized (ex crash logs). the risks you describe could happen to any app out there today (google, facebook, etc), and yet all those apps are also not open source.

walsalam 3alaikum.

**Comment by yFotouh** [comment]
Al salam 3alikum,
Sorry to interfere, but this is the first time to know that quran android is not open source.
So if i take a part of the code as a feature and implement it in another application, would this be illegal?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
there is no matter of legal/illegal here - Quran was open sourced for a long time - several years, since we first released it.

we removed the code and are continuing development without the code being published anymore after discovering many of the things people have been doing with our code - we document some of them in the README.md and more on my blog post here - http://helw.net/2015/08/09/quran-android-no-longer-open-source/.

the only reason we are removing the source is to make it just a little bit more difficult for people to do the kinds of malicious things they are doing today.

please let me know if you have more questions.
walsalam 3alaikum.

**Comment by yFotouh** [comment]
al salam 3alikum,
i was concerned since i have an old source code and was going to take the translation and tafseer feature in another quran project without of coarse taking UI designs or placing ads , but this project was cancelled any way , i'm only was asking if i had continued with this would i be doing something wrong?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
you are welcome to doing that - our main condition has always been to keep respect for the Quran and not do the kinds of things people have been doing.

in your case specifically @yFotouh, since you contributed before, i have no problem giving you access to the new code if you'd rather contribute your ideas to Quran instead of building a new Quran app.
walsalam 3alaikum.

**Comment by yFotouh** [comment]
al salamu 3alkum,
I see know your concerns.
jazakum allahu khayran.

**Comment by ens4dz** [comment]
Al salam 3alikum,
thanks for replay. 
there are a lot of big open source like Firefox,Debian and other android sources:
( https://f-droid.org/repository/browse/ )
not everyone can compile application and edit theme, 
I believe that there are other choice than closing the source, 
there are many open source project but non-free to redistribute, i don't know wiche  source_software_licenses uses .
( https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses )
جزاك الله خيرا

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i am a big proponent of open source, which is why Quran was open sourced in the first place. however, like i said, it hasn't been worth it - most of the contributors to Quran are people i know personally (with very few exceptions), and the number of people who re-released the app after modifying it in an unacceptable way match (or exceed) the number of people who contribute to Quran.

the license doesn't matter - i had very clear terms on the github page, but that didn't stop people from doing whatever they want to do.

walsalam 3alaikum.

**Comment by ens4dz** [comment]
ok.
after all, it sad news for me.
i am gonna try to extract images from my phone and compress size theme as much possible, 
Glad to hear SALAM at: ens4dz [atttt] gmail.com 

^__^

**Comment by ozbek** [comment]
Is there any way outsiders can contribute now except reporting issues? Probably a paid account here at GitHub or moving to Bitbucket is an option?

**Comment by ahmedre** [comment]
@ozbek i gave you access to the private repo the same day i closed it - please let me know if you never got it and i can check insha'Allah.

**Comment by ozbek** [comment]
OK I see it now, jazak Allah.

I remember receiving notification from Github when you added me to that repo, but was not able to take a look at that time. I thought that that was this same repo that went private.

**Comment by ens4dz** [comment]
suggestion:
https://github.com/quran/quran.com-images/issues/4
