### ISSUE TITLE
Use separate service for UI localization?

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#593]
Now that the app is _closed-source_, not all translators have means to send pull requests.
So, should we use other translation service providers like transifex for UI strings?

**Comment by ahmedre** [comment]
funny that you should say that - yesterday, i set up [weblate](http://weblate.org) for this purpose - got it working with Quran, but haven't been able to make it work with github pull requests yet (seems like a bug, so i filed a ticket against them about it yesterday).

planning on moving forward with it insha'Allah (even if i can't get github pull requests working) since, overall, it looks like a great tool.

**Comment by ozbek** [comment]
:+1: 
Looking forward to it.

**Comment by ozbek** [comment]
The precursor (https://github.com/quran/quran_android/issues/591) for this issue is no longer valid. So, if you do not wish to continue to work on weblate, that's fine with me. This issue can be closed.
On the other hand, having a weblate like service would enable people without coding skills to contribute in UI translations.
I am OK with either resolution.

**Comment by ozbek** [comment]
Not relevant anymore, closing.
