### ISSUE TITLE
Set project titles as untranslatable

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#600]
There are several third-party projects used in the app. Titles of some of them seem to be impossible to translate into other languages, such as:

 - QuranicAudio
 - EveryAyah
 - Tanzil
 - Noorhidayat

I suggest to set them `translatable="false"`. What do you think?

**Comment by ahmedre** [comment]
i debated over this for a while, and didn't do it at the time because you translated Electronic Mushaf's site string (and, arguably, it should be translated because it has a different name in Arabic than it does in English).

i agree though that these probably shouldn't be translated (though tanzil and noorhidayat are easy to write in arabic, for example). i am ok with whatever here.
