### ISSUE TITLE
Warsh

### ISSUE THREAD

**Issue by g360230** [quran/quran_android#629]
New bug to track warsh mushafs integration.

**Comment by g360230** [comment]
salmou 3alykom
@ahmedre 
New bug to track warsh mushafs integration

**Comment by g360230** [comment]
Bug report :
We have prepared files for qira2a of warsh (way of asbahani), that you can find in the following URL :
https://www.dropbox.com/sh/vxgnpc92ksphhok/AAAcE9G1BdQ-3hBhv0rGBNRHa?dl=0
Actually we are fixing some issues in ayah selection (not very bad issues). 
We have also found audio files to add them from http://www.versebyversequran.com/site/get-mp3/
- Yassine Al jaza2iri
- AbdulBassit AbduSsamad
- Ibrahim aldosary

Can we have a version for Warsh qira2a (way of asbahani) as we have done for Qaloon?

**Comment by g360230** [comment]
Salamou 3alykom

bellow the last news:
-1- all image are OK: link : to be updated (in this week)
-2- data base selection OK link to be updated (in this week)
-3- audio in progress

we suggest that we uploading only the image and data base as same of qaloon version.

raby yberek fiik

**Comment by ahmedre** [comment]
awesome, looking forward to it insha'Allah - what about the page and ayah boundaries?

**Comment by g360230** [comment]
Salamou 3alykom

We suggest to generate first Warsh release without audio.
We have prepared all sourate images and visual selection database file. You can find all that in the following link : https://www.dropbox.com/sh/vxgnpc92ksphhok/AAAcE9G1BdQ-3hBhv0rGBNRHa?dl=0
So you can generate Warsh application and upload it in play store.
In futre steps we will add audio file.

raby yberek fiik

**Comment by ahmedre** [comment]
wa3laikum alsalam -
there are 3 "ayah by ayah" warsh recitations on everyayah.com - should we use one or more of them? sheikh AbdulBasit, Ibraheem al Dosary, and Yassir al Jaza2iry.
walsalam 3alaikum.

**Comment by g360230** [comment]
salamou 3alykom,

We want to do the same thing as with qaloon : generating a version without audio to maximize number of downloads, then another one which will be the final release with audio files.

For the moment, we still working on qaloon's audio files (Huthaifi). it left only 40% to validate and listen to the quran in the application.
After delivering the Huthaifi audio files, we'll integrate, validate and listen Al Dosary audio files bi ithn elleh.
 
beraka Allahou fik

**Comment by g360230** [comment]
Sallem Aleykom, 

Is there any news about Warsh application? 
We want to publish the application on Playstore before Holy Ramadhan month. Can you publish no audio version till we validate/correct audio for Al Dosary recitator.
If you insist on complete Warsh version including audio, you can publish actual audio files and we will correct possible errors later (as an update).
Audio files are accessible from http://www.everyayah.com/data/warsh/warsh_ibrahim_aldosary_128kbps/000_versebyverse.zip.
Total size is nearly 2GB. If we compress it to 96 kbp/s audio quality, we can reduce this size to just 1 GB.
What do you think ?
raby yberek fik.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
insha'Allah - we have time, since i'll probably push this out with the next Quran for Android release. i'll start working on it though in the next week or two to make sure things are ready to go.

one question: i remember last time i looked at a Warsh mushaf, there were some subtle differences in the verses (ex the mushaf had 6214 ayat instead of 6236, and, for example, sura Baqrah is 285 ayat instead of 286 because "alif laam meem - thalika alkitabu la rayba feeh" is one ayah, and many similar differences throughout). did you account for this and/or can you help with it if so?

jazakAllah khairan,
walsalam 3alaikum

**Comment by g360230** [comment]
Sallem Aleykom,
Difference in eyah counting is not dependant on Riwayah (Warsh, Qaloun, Hafs, ...). There are several eyah counting "schools" : Bassra, Koufah, Mashriq, Maghrib.
For more details, you can visit this link < http://fatwa.islamweb.net/fatwa/index.php?page=showfatwa&Option=FatwaId&Id=173515 >.
What we proposed there is no difference between Mushaf and recitation.
Beraka Allah fika.

**Comment by ahmedre** [comment]
@g360230 i pushed a revision for building the warsh version of the app. will need your help with the credits strings for warsh (where the pages came from especially). let's try to get one audio recitation in since i am not planning an immediate release right now if that's ok?

also, let's see if we can get a different colored icon (right now, i am using Qaloon's).

one remaining thing i need to do is to unzip the files on the server so that downloading page by page works also (right now it doesn't work).

**Comment by g360230** [comment]
Salamo aleikom,
- You can find Warsh Icon from (red icon for warsh):
https://github.com/quran/quran_android/issues/355#issuecomment-111933991
- credits string for warsh is the same as qualoun: "nous-mêmes"
- uploading audio files is in progress (validation 25%) ...
Could you please geranrate the new apk files to continuing validation the audio source.
Beraka Allah fika.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
sounds good insha'Allah:
1. the icon - i reached out to the brother for it since i lost the original high res image, but insha'Allah will do this.
2. sounds good
3. let me know when audio is done so i only have to do the whole download/upload scenario once

you can already build an apk using:
`./gradlew assembleWarshDebug`

though i need to upload sheikh Dosary when you are done and update the recitations to point to their location on the server.

**Comment by g360230** [comment]
Sallem Aleykom,

Warsh audio recitation is beeing validated with current Mushaf. We arrived nearly 34 hizb. No major audio problem is beeing detected.
So we suggest to upload Warsh application in Play Store with audio activated as soon as possible. Specilally if  Holy Ramadhan will come in few weeks.
We will solve probably detected problems after deploiment.

Beraka Allah fika.

**Comment by g360230** [comment]
Sallem Aleykom,

Audio validation is gooing faster and faster. Only 14 sourate are missing (6,7,9,16,17,18,20,21,22,23,24,25,26,27)
All the team members are excited and wait the relase of new Warsh application on Play Store !
Beraka Allah fika.

**Comment by g360230** [comment]
Assalam Alaykom
Audio validation is complete.
Please find files in link below  
https://drive.google.com/drive/folders/0B9PxvANrtK1BMUhvYTdaUmZKczQ

**Comment by ahmedre** [comment]
added sheikh dosary and pushed the updated files on the servers.

one question - did you find any mistakes, so we can upload the everyayah files if needed?
jazakAllah khairan

**Comment by g360230** [comment]
Salmaou 3alykom,

Baraka allahou fik for the push, 
Yes, we found errors during the validation of the audio
Did you see qaloon delivery on issue #355 ?

 Baraka ALLAH fik

**Comment by ahmedre** [comment]
wa3laikum alsalam,
done also.
insha'Allah will push this next time i push a Quran android update, which will be sometime before (or close to) Ramadan insha'Allah.
i'll close this for now, but please re-open or open a new ticket if there's anything else.

jazakAllah khairan for doing this!
walsalam 3alaikum

**Comment by ahmedre** [comment]
live now al7amdulillah - jazakumAllah khairan for making this happen! https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.warsh

**Comment by g360230** [comment]
السلام عليكم
 
الحمد لله جزاكم الله خيرا وجعله في ميزان حسناتكم
لا تنسونا من صالح دعائكم في رمضان 

بارك الله فيكم
