### ISSUE TITLE
Feature: Reading History

### ISSUE THREAD

**Issue by jawadkho** [quran/quran_android#691]
Use-case: For daily reading, I can go back to my last reading position using the 'last page' button. However, if I go to another page -- for the purposes of reading another surah, surah al-kahf on Fridays, memorisation, revision etc -- I lose my last reading position. I want to be able to switch between two or more positions with ease.

Using the current features available: I could achieve this by bookmarking the page I was last reading and then go to the new position and switch back similarly. This has a lot of steps and in most cases, I forget to do so and lose my position.

Note: I say reading history but the main point is to address the use-case rather than actually having a history. That's just the first thing that popped into my head.

**Comment by ahmedre** [comment]
quoting from a conversation we had offline:

> on another Quran app that had said jump feature, we eventually simplified it to just "jump to the last" (i.e. maintain the last 2 jump points only as opposed to an infinite history) - because usage was very low
> on top of my head, one simple solution is an option to automatically bookmark jump regions for example (i.e. implement it as part of bookmarks for example)

other things we could do include a temporary (session specific) cache of places jumped - so the behavior stays the same, but we can show the last x places jumped in bookmarks as a sort of history. still other things we can think about is how to design moving bookmarks (and add some intelligence to them so that they don't automatically update when they shouldn't).

i think we should do this, but we should do it in a way that it's a "power user" feature without confusing everyday use by people.

interested in hearing ideas from everyone on their thoughts on good ways to do this (cc @ozbek @hakimrie).

**Comment by jawadkho** [comment]
Ah I didn't understand that idea earlier (I was reading quite late at night) but that sounds good. So basically have sessions (or bookmark sessions) which using some sort of intelligence can track reading points. For example, if I'm on page 64 and go to another page (from the menu) such as 450 each will have its own session. If I go back to 64 (from the menu) then it continues recording from that point. Did I get that right?

Another idea I had was if we use tabs like the Chrome or Wikipedia apps. It'd simplify quite a few things. And users could close them whenever they like. It would be a familiar concept to many users (but potentially a bit confusing in this type of app).

**Comment by MalikSaabSays** [comment]
السلام عليكم 
If I may pitch in...
Reading history pane could record history for a fix amount of time, like last 15 days or 30 days, continually replacing oldest with new.

**Comment by jawadkho** [comment]
@MalikSaabSays Yep, that would be the simplest way to do it.
