### ISSUE TITLE
Add kanzul iman translation.

### ISSUE THREAD

**Issue by shahrukhmlk** [quran/quran_android#698]
السلام عليكم
I want to add a new translation to your project. This translation known as Kanzul Iman is pretty famous in urdu speaking countries. Kindly tell me if it can be done.

**Comment by shahrukhmlk** [comment]
I already have it in database format ready with all metadata. Kindly tell me how to add it.

**Comment by ATouhou** [comment]
wa aleykoum salam.
Is it in english or urdu? If english, could you share it in a link here :-) ?

**Comment by shahrukhmlk** [comment]
It is originally in urdu. Please tell me the schema and I will adapt the database to it and upload it.

**Comment by shahrukhmlk** [comment]
I also have it in english.

**Comment by shahrukhmlk** [comment]
Can somebody help me add it??

**Comment by shahrukhmlk** [comment]
Still waiting?

**Comment by shahrukhmlk** [comment]
???

**Comment by Furqaan92** [comment]
What happened? Please add the translation to GitHub so we add it to quran.com

**Comment by TGLTClutch** [comment]
Kind of odd that the  Ma'riful Quran of Usmani is available, Tafheem ul quran of Mawdudi translation as well. But somehow Kanzul Iman of Imam Ahmed Rida Khan is left out? There is an Ios app named Kanzul Iman it has a nice interface and font. It  even has an  english translation it.  No android app, to the best of my knowledge, has anything of similar level of elegance. 
i hope you guys can add it since it is a very beneficial translation written by a renowned defender of Orthodox Sunni Creed.

**Comment by ahmedre** [comment]
@naveed-ahmad do we have this on Quran.com that we can add to the app?

**Comment by nadeem33n** [comment]
Can I get the Quran API with translation and audio?

**Comment by ozbek** [comment]
> Can I get the Quran API with translation and audio?

Yes. Please see https://api-docs.quran.foundation website.

**Comment by mdnumanraza** [comment]
> I also have it in english.

Assalamu alaikum brother, can you please share the link of DB or dataset of Kanzul Iman translation you have in english, I wanna integrate in my application

update: nvm, i found the translation using en.ahmedraza
