### ISSUE TITLE
Unable to download audio due to network error

### ISSUE THREAD

**Issue by adliabdoh** [quran/quran_android#723]
I have a technical issue with the Qur'an app. When I try to download the Abu Bakr Shatri (gapless) it always stops at the 41st surah and an error message pops up (network error, trying to resume) followed by "could not download due to network error). 

I tried going to the 42nd surah and tried to download the audio but it had the same message

Please assist

**Comment by ahmedre** [comment]
this isn't a bug - just that sura 42 is missing :(
http://download.quranicaudio.com/quran/abu_bakr_ash-shaatree/

i think it used to be there, but i had to take it down when i got some random "cease and desist - remove these 2 files or we'll make your service provider take your servers down" message through the servers :(

download it manually for now from the `removed/` subdirectory of the directory above, put it in the right place, and you should be good to go.

closing since not a Quran for Android bug.
