### ISSUE TITLE
Introduce functional/UI testing

### ISSUE THREAD

**Issue by hosainnet** [quran/quran_android#750]
Salam. 

As Android uses a lot of final/static classes and methods, unit testing can be a little difficult and it would be good to have some more test coverage in the form of functional/ui tests (testing against a running app)

Some things to consider:

- What framework to use? e.g [Espresso](https://developer.android.com/training/testing/ui-testing/espresso-testing.html)?
- How will tests run on CI
- All external HTTP calls should be mocked  (something like [this](https://github.com/Confluex/confluex-mock-http) could work well)
- Use a decent test runner ([Spoon comes to mind](https://github.com/square/spoon))

Maybe for the purposes of this task, we can setup the framework and pick just a single activity to try an test it first, then use it going forwards.

What is everyone's thought on this?

**Comment by ahmedre** [comment]
wa3laikum alsalam -
definitely - i've been rewriting a lot of code to try to split out ui logic and make things easier to test. do you want to take this?

- +1 for Espresso
- CI - Travis should support it, but if not, we can switch to CircleCI since they also have free plans for open source projects that we can use.
- Mocking HTTP - i've used OkHttp's MockServer to test [TranslationManagerPresenter](https://github.com/quran/quran_android/blob/master/app/src/test/java/com/quran/labs/androidquran/presenter/translation/TranslationManagerPresenterTest.java) and it works pretty well without adding any new dependencies.
- no problem using Spoon, but do we need it? i thought part of its use was running tests on multiple devices and capturing screenshots?

walsalam 3alaikum

**Comment by hosainnet** [comment]
OK great, yes I'll take it inshallah.

We might need to think about how we structure our tests, e.g if we want to put Espresso tests in a different package etc.

Re Spoon, you're right it's not that necessary but it generates a neat HTML report and can take screenshots which is handy if we're running tests headless. I'll leave it out for now but we can add it later if needed.
