### ISSUE TITLE
highligh overlap

### ISSUE THREAD

**Issue by mrash14** [quran/quran_android#951]
![image_20_05_2018_925](https://user-images.githubusercontent.com/6044543/40277730-8b0258d6-5c39-11e8-874f-efdfe78e9b90.jpg)
![image_20_05_2018_499](https://user-images.githubusercontent.com/6044543/40277724-7acb65d4-5c39-11e8-8056-a097f2547f43.jpg)
![image_20_05_2018_189](https://user-images.githubusercontent.com/6044543/40277731-8ecba350-5c39-11e8-89f1-37a8f2f71f15.jpg)

in page 17

**Comment by murtraja** [comment]
@ahmedre I was not able to reproduce 1 or 3, but I was able to reproduce no. 2 on edbd926 ( Bump version to 2.9.2-p3), images_1024, Samsung Galaxy Grand 2

Upon investigating further, I found that secondIsFullLine turns out to be false during consolidating lines 12 & 13 (the first two lines of 2:111)

The reason being that firstRect.left is 37 and lastRect.left is 48, the difference turns out to be 11 which is NOT LESS than PIXEL_THRESHOLD. By changing PIXEL_THRESHOLD from 10 to 12, it "seemingly" fixes the highlight overlapping.

**Comment by murtraja** [comment]
![bug_1_7](https://user-images.githubusercontent.com/7806954/52536872-fb358600-2d85-11e9-9a5f-0e2a2d1bff91.png)
I found this highlight overlapping. Couldn't investigate much but it goes to a condition where we inform Crashlytics that the verse couldn't be consolidated (the condition where topSize + bottomSize > 4)

**Comment by ahmedre** [comment]
jazakAllah khairan for this very helpful investigation - i have to look at the code again, but we can change the threshold in sha' Allah to fix that first problem. i'll have to refresh my memory on the code for fixing the second one. if it is a data issue though, we can always update the highlighting database as well.

**Comment by murtraja** [comment]
@ahmedre I think I know the reason for the double highlight and have managed to come up with this solution.
```
diff --git a/app/src/main/java/com/quran/labs/androidquran/model/quran/CoordinatesModel.java b/app/src/main/java/com/quran/labs/androidquran/model/quran/CoordinatesModel.java
index 628dde41..933fa160 100644
--- a/app/src/main/java/com/quran/labs/androidquran/model/quran/CoordinatesModel.java
+++ b/app/src/main/java/com/quran/labs/androidquran/model/quran/CoordinatesModel.java
@@ -93,7 +93,11 @@ public class CoordinatesModel {
         Crashlytics.log("current verse: " + key);
         Crashlytics.logException(new IllegalStateException("Lines not properly joined for verse"));
         result.addAll(top);
-        result.addAll(bottom);
+        if (bottom.size() > 1) {
+          result.addAll(bottom.subList(1, bottom.size()));
+        } else {
+          result.addAll(bottom);
+        }
         return result;
       } else {
         // re-consolidate top and middle again, since middle may have changed

```

I am attaching some images that will help you understand the problem

**Buggy case:**

The `top` while consolidating 1:7. `topSize=3`
[image helper tool](https://quran-android-images-helper.herokuapp.com/?safah=1&highlight=RectF(220.0,%20566.0,%20487.0,%20636.0)%0ARectF(298.0,%20636.0,%20487.0,%20660.0)%0ARectF(298.0,%20660.0,%20729.0,%20734.0))
![bug_1](https://user-images.githubusercontent.com/7806954/54084103-8a689600-4352-11e9-9777-79b0701222e3.png)

The `bottom` while consolidating 1:7. `bottomSize=3`
[image helper tool](https://quran-android-images-helper.herokuapp.com/?safah=1&highlight=RectF(298.0,%20660.0,%20729.0,%20734.0)%0ARectF(385.0,%20734.0,%20729.0,%20747.0)%0ARectF(385.0,%20747.0,%20639.0,%20811.0))
![bug_2](https://user-images.githubusercontent.com/7806954/54084102-8a689600-4352-11e9-9d54-3b53304f6671.png)

Note: `topSize + bottomSize > 4` 

**Normal case:**

The `top` while consolidating 2:107. `topSize=2`
![normal_1](https://user-images.githubusercontent.com/7806954/54084104-8b012c80-4352-11e9-9111-d4c11a4a3b85.png)

The `bottom` while consolidating 2:107. `topSize=2`
![normal_2](https://user-images.githubusercontent.com/7806954/54084105-8b012c80-4352-11e9-9f7b-cc718bcede6f.png)

Note: `topSize + bottomSize <= 4`

**Comment by ahmedre** [comment]
jazakAllah khairan! i just searched Fabric and there are a bunch more of these - 58:18, 53:23, 25:62, 50:22, 76:21, 39:69, 17:110, 2:109, 6:96, 49:3, 2:107, 9:98, 10:57, 5:27, and probably a bunch more.

let me try to remember what the code was doing and then re-read your suggestion afterwards. jazakAllah khairan, really appreciate your help with this!

**Comment by murtraja** [comment]
I checked all the above ayahs by jumping to them and they don't have any double highlight overlaps. (maybe I should first remove my fix and then check those again to really verify this) 

I strongly recommend that we must check for them in other image types (I checked on 1024, I have an old Samsung Galaxy Grand 2) because the original issue creator had issues with 2:107, but in my case, I didn't have them.

**Comment by ahmedre** [comment]
i checked about half of them on 1260 images and they had the issue. perhaps you're not seeing it with these either because your fix fixed it or because they don't happen on those image sizes (or a combination of both).

**Comment by murtraja** [comment]
@ahmedre, from the list that you have given, I could reproduce the double highlight issue with the following ayahs using 1260. The solution here is to set `PIXEL_THRESHOLD` to 13 (as the highest difference is 12 in No. 2) but of course, with a different set of images, this may not be the case, we might have to further increase it. (it might make sense to calculate `PIXEL_THRESHOLD` depending on image resolution, it might be simply 1% of the resolution)

| No. | Ayah  | wrong consolidation | difference | Remarks                               |
|-----|-------|---------------------|------------|---------------------------------------|
| 1   | 58:18 | bottom              | 10         | last line **innahum** coords can be fixed |
| 2   | 25:62 | bottom              | 12         | -                                     |
| 3   | 50:22 | top                 | 11         |                                       |
| 4   | 6:96  | bottom              | 10         | last line **aziz** coords can be fixed    |
| 5   | 49:3  | top                 | 10         |                                       |
| 6   | 10:57 | top                 | 11         |                                       |

whenever there is a wrong consolidation, its size becomes 3, and its counterpart's size is 2, making a total of 5 which is greater than 4, hence we report it. E.g. consider No. 1, its bottomSize will be 3, and its topSize will be 2

Also, one interesting thing here is that the fix for 1:7 stated [here](https://github.com/quran/quran_android/issues/951#issuecomment-471279103) might potentially fix all the above issues without changing `PIXEL_THRESHOLD` value

**Comment by murtraja** [comment]
For 1920, the difference for 25:62 turns out to be 16 (1843-1827)

**Comment by ahmedre** [comment]
@murtraja jazakAllah khairan for your awesome help with this.

the primary fix for the double highlighting here is to remove all duplicate rectangles (or rectangles that include others). your fix does this (by removing the first one from bottom) - i did something similar by checking instead of just removing it (whether it matches the last one from top or one of them includes the other).

it leaves the cases where the drawing isn't perfect on the edges (as you mentioned above about "coords can be fixed"). making `PIXEL_THRESHOLD` larger fixes this (and, because it drops us out of the `consolidate` case where we end up drawing duplicate rectangles, it fixes a lot of the duplicate cases automatically as you had mentioned also without the primary fix) - but doesn't fix all the issues (ex 1:7). also, how big to make `PIXEL_THRESHOLD` is tricky - i.e. as you said, 12 should do the trick for most of 1260 pages, but i found a case in the 1260 pages (50:22) where threshold has to be set to 16 for the drawing to look correct. made it 1.5% of the page width for now.

really appreciate your help @murtraja and jazakAllah khairan for both writing the debug tool and helping me figure out this problem! and jazakAllah khairan @mrash14 for reporting!

**Comment by mrash14** [comment]
thanks @ahmedre
