### ISSUE TITLE
Please fix the mistake!!!

### ISSUE THREAD

**Issue by Shereennoureldin** [quran/quran_android#957]
Please have the quran revised.. verse 176 surat Ash-Shu'ara " al ayka" is missing an alef

**Comment by ahmedre** [comment]
please double check your mus7af - it's correct. these images are from King Fahd's Quran Complex, so they are the same images used for printing a good percentage of the masa7if in the world.

![2018-06-07 23 12 39](https://user-images.githubusercontent.com/47771/41121075-75a1edee-6aa8-11e8-8567-3f567eb1bf11.jpg)

**Comment by Shereennoureldin** [comment]
This is a screenshot from my quran android application. The mistake is
there!

**Comment by ahmedre** [comment]
your screenshot didn't attach - please re-attach. comparing the app to the mus7af it's exactly the same:

![screenshot_1528482817](https://user-images.githubusercontent.com/47771/41174888-610b985c-6b6c-11e8-96f6-cfe3780b22f3.png)

if what you mean is "in the translation, there's an alif and there shouldn't be" - it's not an error - it's due to the difference of writing from a pure uthmani script (in the mus7af) and an imlaei (as it is written in modern arabic) script. both are pronounced the exact same and both are correct. because this type of difference confuses a lot of people, we intend on trying to make the text in the translation view and the images the same in the near future in sha' Allah.

![screenshot_1528483159](https://user-images.githubusercontent.com/47771/41175015-cb3055f6-6b6c-11e8-8195-ad3c39560845.png)

**Comment by ahmedre** [comment]
closing. please re-open if you still think there's a mistake or issue.
